//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="CancellationAIFMRecordInfo" type="{}ComplexCancellationAIFMRecordInfoType"/>
 *         &lt;element name="AIFMRecordInfo" type="{}ComplexAIFMRecordInfoType"/>
 *       &lt;/choice>
 *       &lt;attribute name="ReportingMemberState" use="required" type="{}CountryCodeType" />
 *       &lt;attribute name="Version" use="required" type="{}VersionType" />
 *       &lt;attribute name="CreationDateAndTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cancellationAIFMRecordInfoOrAIFMRecordInfo"
})
@XmlRootElement(name = "AIFMReportingInfo")
public class AIFMReportingInfo {

    @XmlElements({
        @XmlElement(name = "CancellationAIFMRecordInfo", type = ComplexCancellationAIFMRecordInfoType.class),
        @XmlElement(name = "AIFMRecordInfo", type = ComplexAIFMRecordInfoType.class)
    })
    protected List<Object> cancellationAIFMRecordInfoOrAIFMRecordInfo;
    @XmlAttribute(name = "ReportingMemberState", required = true)
    protected String reportingMemberState;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "CreationDateAndTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateAndTime;

    /**
     * Gets the value of the cancellationAIFMRecordInfoOrAIFMRecordInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cancellationAIFMRecordInfoOrAIFMRecordInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCancellationAIFMRecordInfoOrAIFMRecordInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexCancellationAIFMRecordInfoType }
     * {@link ComplexAIFMRecordInfoType }
     * 
     * 
     */
    public List<Object> getCancellationAIFMRecordInfoOrAIFMRecordInfo() {
        if (cancellationAIFMRecordInfoOrAIFMRecordInfo == null) {
            cancellationAIFMRecordInfoOrAIFMRecordInfo = new ArrayList<Object>();
        }
        return this.cancellationAIFMRecordInfoOrAIFMRecordInfo;
    }

    /**
     * Gets the value of the reportingMemberState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingMemberState() {
        return reportingMemberState;
    }

    /**
     * Sets the value of the reportingMemberState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingMemberState(String value) {
        this.reportingMemberState = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the creationDateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateAndTime() {
        return creationDateAndTime;
    }

    /**
     * Sets the value of the creationDateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateAndTime(XMLGregorianCalendar value) {
        this.creationDateAndTime = value;
    }

}
