//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssetTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssetTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SEC_CSH"/>
 *     &lt;enumeration value="SEC_LEQ"/>
 *     &lt;enumeration value="SEC_UEQ"/>
 *     &lt;enumeration value="SEC_CPN"/>
 *     &lt;enumeration value="SEC_CPI"/>
 *     &lt;enumeration value="SEC_SBD"/>
 *     &lt;enumeration value="SEC_MBN"/>
 *     &lt;enumeration value="SEC_CBN"/>
 *     &lt;enumeration value="SEC_CBI"/>
 *     &lt;enumeration value="SEC_LON"/>
 *     &lt;enumeration value="SEC_SSP"/>
 *     &lt;enumeration value="DER_EQD"/>
 *     &lt;enumeration value="DER_FID"/>
 *     &lt;enumeration value="DER_CDS"/>
 *     &lt;enumeration value="DER_FEX"/>
 *     &lt;enumeration value="DER_IRD"/>
 *     &lt;enumeration value="DER_CTY"/>
 *     &lt;enumeration value="DER_OTH"/>
 *     &lt;enumeration value="PHY_RES"/>
 *     &lt;enumeration value="PHY_CTY"/>
 *     &lt;enumeration value="PHY_TIM"/>
 *     &lt;enumeration value="PHY_ART"/>
 *     &lt;enumeration value="PHY_TPT"/>
 *     &lt;enumeration value="PHY_OTH"/>
 *     &lt;enumeration value="CIU_OAM"/>
 *     &lt;enumeration value="CIU_NAM"/>
 *     &lt;enumeration value="OTH_OTH"/>
 *     &lt;enumeration value="NTA_NTA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssetTypeType")
@XmlEnum
public enum AssetTypeType {

    SEC_CSH,
    SEC_LEQ,
    SEC_UEQ,
    SEC_CPN,
    SEC_CPI,
    SEC_SBD,
    SEC_MBN,
    SEC_CBN,
    SEC_CBI,
    SEC_LON,
    SEC_SSP,
    DER_EQD,
    DER_FID,
    DER_CDS,
    DER_FEX,
    DER_IRD,
    DER_CTY,
    DER_OTH,
    PHY_RES,
    PHY_CTY,
    PHY_TIM,
    PHY_ART,
    PHY_TPT,
    PHY_OTH,
    CIU_OAM,
    CIU_NAM,
    OTH_OTH,
    NTA_NTA;

    public String value() {
        return name();
    }

    public static AssetTypeType fromValue(String v) {
        return valueOf(v);
    }

}
