//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexShareClassIdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexShareClassIdentifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShareClassNationalCode" type="{}ShareClassNationalCodeType" minOccurs="0"/>
 *         &lt;element name="ShareClassIdentifierISIN" type="{}ISINInstrumentIdentificationType" minOccurs="0"/>
 *         &lt;element name="ShareClassIdentifierCUSIP" type="{}CusipCodeType" minOccurs="0"/>
 *         &lt;element name="ShareClassIdentifierSEDOL" type="{}SedolCodeType" minOccurs="0"/>
 *         &lt;element name="ShareClassIdentifierTicker" type="{}TickerCodeType" minOccurs="0"/>
 *         &lt;element name="ShareClassIdentifierRIC" type="{}RICCodeType" minOccurs="0"/>
 *         &lt;element name="ShareClassName" type="{}StringRestricted300Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexShareClassIdentifierType", propOrder = {
    "shareClassNationalCode",
    "shareClassIdentifierISIN",
    "shareClassIdentifierCUSIP",
    "shareClassIdentifierSEDOL",
    "shareClassIdentifierTicker",
    "shareClassIdentifierRIC",
    "shareClassName"
})
public class ComplexShareClassIdentifierType {

    @XmlElement(name = "ShareClassNationalCode")
    protected String shareClassNationalCode;
    @XmlElement(name = "ShareClassIdentifierISIN")
    protected String shareClassIdentifierISIN;
    @XmlElement(name = "ShareClassIdentifierCUSIP")
    protected String shareClassIdentifierCUSIP;
    @XmlElement(name = "ShareClassIdentifierSEDOL")
    protected String shareClassIdentifierSEDOL;
    @XmlElement(name = "ShareClassIdentifierTicker")
    protected String shareClassIdentifierTicker;
    @XmlElement(name = "ShareClassIdentifierRIC")
    protected String shareClassIdentifierRIC;
    @XmlElement(name = "ShareClassName", required = true)
    protected String shareClassName;

    /**
     * Gets the value of the shareClassNationalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareClassNationalCode() {
        return shareClassNationalCode;
    }

    /**
     * Sets the value of the shareClassNationalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareClassNationalCode(String value) {
        this.shareClassNationalCode = value;
    }

    /**
     * Gets the value of the shareClassIdentifierISIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareClassIdentifierISIN() {
        return shareClassIdentifierISIN;
    }

    /**
     * Sets the value of the shareClassIdentifierISIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareClassIdentifierISIN(String value) {
        this.shareClassIdentifierISIN = value;
    }

    /**
     * Gets the value of the shareClassIdentifierCUSIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareClassIdentifierCUSIP() {
        return shareClassIdentifierCUSIP;
    }

    /**
     * Sets the value of the shareClassIdentifierCUSIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareClassIdentifierCUSIP(String value) {
        this.shareClassIdentifierCUSIP = value;
    }

    /**
     * Gets the value of the shareClassIdentifierSEDOL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareClassIdentifierSEDOL() {
        return shareClassIdentifierSEDOL;
    }

    /**
     * Sets the value of the shareClassIdentifierSEDOL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareClassIdentifierSEDOL(String value) {
        this.shareClassIdentifierSEDOL = value;
    }

    /**
     * Gets the value of the shareClassIdentifierTicker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareClassIdentifierTicker() {
        return shareClassIdentifierTicker;
    }

    /**
     * Sets the value of the shareClassIdentifierTicker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareClassIdentifierTicker(String value) {
        this.shareClassIdentifierTicker = value;
    }

    /**
     * Gets the value of the shareClassIdentifierRIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareClassIdentifierRIC() {
        return shareClassIdentifierRIC;
    }

    /**
     * Sets the value of the shareClassIdentifierRIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareClassIdentifierRIC(String value) {
        this.shareClassIdentifierRIC = value;
    }

    /**
     * Gets the value of the shareClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareClassName() {
        return shareClassName;
    }

    /**
     * Sets the value of the shareClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareClassName(String value) {
        this.shareClassName = value;
    }

}
