//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexMainInstrumentTradedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexMainInstrumentTradedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ranking" type="{}FiveRankingType"/>
 *         &lt;element name="SubAssetType" type="{}SubAssetTypeType"/>
 *         &lt;element name="InstrumentCodeType" type="{}InstrumentCodeTypeType" minOccurs="0"/>
 *         &lt;element name="InstrumentName" type="{}StringRestricted300Type" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ISINInstrumentIdentification" type="{}ISINInstrumentIdentificationType"/>
 *           &lt;element name="AIIInstrumentIdentification" type="{}ComplexAIIInstrumentIdentificationType"/>
 *         &lt;/choice>
 *         &lt;element name="PositionValue" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *         &lt;element name="PositionType" type="{}PositionTypeType" minOccurs="0"/>
 *         &lt;element name="ShortPositionHedgingRate" type="{}UnsignedDecimal15p4Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexMainInstrumentTradedType", propOrder = {
    "ranking",
    "subAssetType",
    "instrumentCodeType",
    "instrumentName",
    "isinInstrumentIdentification",
    "aiiInstrumentIdentification",
    "positionValue",
    "positionType",
    "shortPositionHedgingRate"
})
public class ComplexMainInstrumentTradedType {

    @XmlElement(name = "Ranking", required = true)
    protected BigInteger ranking;
    @XmlElement(name = "SubAssetType", required = true)
    protected SubAssetTypeType subAssetType;
    @XmlElement(name = "InstrumentCodeType")
    protected InstrumentCodeTypeType instrumentCodeType;
    @XmlElement(name = "InstrumentName")
    protected String instrumentName;
    @XmlElement(name = "ISINInstrumentIdentification")
    protected String isinInstrumentIdentification;
    @XmlElement(name = "AIIInstrumentIdentification")
    protected ComplexAIIInstrumentIdentificationType aiiInstrumentIdentification;
    @XmlElement(name = "PositionValue")
    protected BigInteger positionValue;
    @XmlElement(name = "PositionType")
    protected PositionTypeType positionType;
    @XmlElement(name = "ShortPositionHedgingRate")
    protected BigDecimal shortPositionHedgingRate;

    /**
     * Gets the value of the ranking property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRanking() {
        return ranking;
    }

    /**
     * Sets the value of the ranking property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRanking(BigInteger value) {
        this.ranking = value;
    }

    /**
     * Gets the value of the subAssetType property.
     * 
     * @return
     *     possible object is
     *     {@link SubAssetTypeType }
     *     
     */
    public SubAssetTypeType getSubAssetType() {
        return subAssetType;
    }

    /**
     * Sets the value of the subAssetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubAssetTypeType }
     *     
     */
    public void setSubAssetType(SubAssetTypeType value) {
        this.subAssetType = value;
    }

    /**
     * Gets the value of the instrumentCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link InstrumentCodeTypeType }
     *     
     */
    public InstrumentCodeTypeType getInstrumentCodeType() {
        return instrumentCodeType;
    }

    /**
     * Sets the value of the instrumentCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstrumentCodeTypeType }
     *     
     */
    public void setInstrumentCodeType(InstrumentCodeTypeType value) {
        this.instrumentCodeType = value;
    }

    /**
     * Gets the value of the instrumentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentName() {
        return instrumentName;
    }

    /**
     * Sets the value of the instrumentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentName(String value) {
        this.instrumentName = value;
    }

    /**
     * Gets the value of the isinInstrumentIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISINInstrumentIdentification() {
        return isinInstrumentIdentification;
    }

    /**
     * Sets the value of the isinInstrumentIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISINInstrumentIdentification(String value) {
        this.isinInstrumentIdentification = value;
    }

    /**
     * Gets the value of the aiiInstrumentIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAIIInstrumentIdentificationType }
     *     
     */
    public ComplexAIIInstrumentIdentificationType getAIIInstrumentIdentification() {
        return aiiInstrumentIdentification;
    }

    /**
     * Sets the value of the aiiInstrumentIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAIIInstrumentIdentificationType }
     *     
     */
    public void setAIIInstrumentIdentification(ComplexAIIInstrumentIdentificationType value) {
        this.aiiInstrumentIdentification = value;
    }

    /**
     * Gets the value of the positionValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositionValue() {
        return positionValue;
    }

    /**
     * Sets the value of the positionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPositionValue(BigInteger value) {
        this.positionValue = value;
    }

    /**
     * Gets the value of the positionType property.
     * 
     * @return
     *     possible object is
     *     {@link PositionTypeType }
     *     
     */
    public PositionTypeType getPositionType() {
        return positionType;
    }

    /**
     * Sets the value of the positionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionTypeType }
     *     
     */
    public void setPositionType(PositionTypeType value) {
        this.positionType = value;
    }

    /**
     * Gets the value of the shortPositionHedgingRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getShortPositionHedgingRate() {
        return shortPositionHedgingRate;
    }

    /**
     * Sets the value of the shortPositionHedgingRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setShortPositionHedgingRate(BigDecimal value) {
        this.shortPositionHedgingRate = value;
    }

}
