//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:36 PM CET 
//


package com.reportingtool.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ComplexAIFRecordInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexAIFRecordInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FilingType" type="{}FilingTypeType"/>
 *         &lt;element name="AIFContentType" type="{}AIFContentTypeType"/>
 *         &lt;element name="ReportingPeriodStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ReportingPeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ReportingPeriodType" type="{}ReportingPeriodTypeType"/>
 *         &lt;element name="ReportingPeriodYear" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *         &lt;element name="AIFReportingObligationChangeFrequencyCode" type="{}ReportingObligationChangeFrequencyCodeType" minOccurs="0"/>
 *         &lt;element name="AIFReportingObligationChangeContentsCode" type="{}AIFReportingObligationChangeContentsCodeType" minOccurs="0"/>
 *         &lt;element name="AIFReportingObligationChangeQuarter" type="{}ReportingObligationChangeQuarterType" minOccurs="0"/>
 *         &lt;element name="LastReportingFlag" type="{}BooleanType"/>
 *         &lt;element name="Assumptions" type="{}ComplexAssumptionsType" minOccurs="0"/>
 *         &lt;element name="AIFMNationalCode" type="{}AIFMNationalCodeType"/>
 *         &lt;element name="AIFNationalCode" type="{}AIFNationalCodeType"/>
 *         &lt;element name="AIFName" type="{}StringRestricted300Type"/>
 *         &lt;element name="AIFEEAFlag" type="{}BooleanType"/>
 *         &lt;element name="AIFReportingCode" type="{}AIFReportingCodeType"/>
 *         &lt;element name="AIFDomicile" type="{}CountryCodeType"/>
 *         &lt;element name="InceptionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AIFNoReportingFlag" type="{}BooleanType"/>
 *         &lt;element name="AIFCompleteDescription" type="{}ComplexAIFCompleteDescriptionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexAIFRecordInfoType", propOrder = {
    "filingType",
    "aifContentType",
    "reportingPeriodStartDate",
    "reportingPeriodEndDate",
    "reportingPeriodType",
    "reportingPeriodYear",
    "aifReportingObligationChangeFrequencyCode",
    "aifReportingObligationChangeContentsCode",
    "aifReportingObligationChangeQuarter",
    "lastReportingFlag",
    "assumptions",
    "aifmNationalCode",
    "aifNationalCode",
    "aifName",
    "aifeeaFlag",
    "aifReportingCode",
    "aifDomicile",
    "inceptionDate",
    "aifNoReportingFlag",
    "aifCompleteDescription"
})
public class ComplexAIFRecordInfoType {

    @XmlElement(name = "FilingType", required = true)
    protected FilingTypeType filingType;
    @XmlElement(name = "AIFContentType", required = true)
    protected String aifContentType;
    @XmlElement(name = "ReportingPeriodStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reportingPeriodStartDate;
    @XmlElement(name = "ReportingPeriodEndDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reportingPeriodEndDate;
    @XmlElement(name = "ReportingPeriodType", required = true)
    protected ReportingPeriodTypeType reportingPeriodType;
    @XmlElement(name = "ReportingPeriodYear", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar reportingPeriodYear;
    @XmlElement(name = "AIFReportingObligationChangeFrequencyCode")
    protected ReportingObligationChangeFrequencyCodeType aifReportingObligationChangeFrequencyCode;
    @XmlElement(name = "AIFReportingObligationChangeContentsCode")
    protected BigInteger aifReportingObligationChangeContentsCode;
    @XmlElement(name = "AIFReportingObligationChangeQuarter")
    protected ReportingObligationChangeQuarterType aifReportingObligationChangeQuarter;
    @XmlElement(name = "LastReportingFlag")
    protected boolean lastReportingFlag;
    @XmlElement(name = "Assumptions")
    protected ComplexAssumptionsType assumptions;
    @XmlElement(name = "AIFMNationalCode", required = true)
    protected String aifmNationalCode;
    @XmlElement(name = "AIFNationalCode", required = true)
    protected String aifNationalCode;
    @XmlElement(name = "AIFName", required = true)
    protected String aifName;
    @XmlElement(name = "AIFEEAFlag")
    protected boolean aifeeaFlag;
    @XmlElement(name = "AIFReportingCode", required = true)
    protected BigInteger aifReportingCode;
    @XmlElement(name = "AIFDomicile", required = true)
    protected String aifDomicile;
    @XmlElement(name = "InceptionDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar inceptionDate;
    @XmlElement(name = "AIFNoReportingFlag")
    protected boolean aifNoReportingFlag;
    @XmlElement(name = "AIFCompleteDescription")
    protected ComplexAIFCompleteDescriptionType aifCompleteDescription;

    /**
     * Gets the value of the filingType property.
     * 
     * @return
     *     possible object is
     *     {@link FilingTypeType }
     *     
     */
    public FilingTypeType getFilingType() {
        return filingType;
    }

    /**
     * Sets the value of the filingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilingTypeType }
     *     
     */
    public void setFilingType(FilingTypeType value) {
        this.filingType = value;
    }

    /**
     * Gets the value of the aifContentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFContentType() {
        return aifContentType;
    }

    /**
     * Sets the value of the aifContentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFContentType(String value) {
        this.aifContentType = value;
    }

    /**
     * Gets the value of the reportingPeriodStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingPeriodStartDate() {
        return reportingPeriodStartDate;
    }

    /**
     * Sets the value of the reportingPeriodStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingPeriodStartDate(XMLGregorianCalendar value) {
        this.reportingPeriodStartDate = value;
    }

    /**
     * Gets the value of the reportingPeriodEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingPeriodEndDate() {
        return reportingPeriodEndDate;
    }

    /**
     * Sets the value of the reportingPeriodEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingPeriodEndDate(XMLGregorianCalendar value) {
        this.reportingPeriodEndDate = value;
    }

    /**
     * Gets the value of the reportingPeriodType property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingPeriodTypeType }
     *     
     */
    public ReportingPeriodTypeType getReportingPeriodType() {
        return reportingPeriodType;
    }

    /**
     * Sets the value of the reportingPeriodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingPeriodTypeType }
     *     
     */
    public void setReportingPeriodType(ReportingPeriodTypeType value) {
        this.reportingPeriodType = value;
    }

    /**
     * Gets the value of the reportingPeriodYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingPeriodYear() {
        return reportingPeriodYear;
    }

    /**
     * Sets the value of the reportingPeriodYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingPeriodYear(XMLGregorianCalendar value) {
        this.reportingPeriodYear = value;
    }

    /**
     * Gets the value of the aifReportingObligationChangeFrequencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingObligationChangeFrequencyCodeType }
     *     
     */
    public ReportingObligationChangeFrequencyCodeType getAIFReportingObligationChangeFrequencyCode() {
        return aifReportingObligationChangeFrequencyCode;
    }

    /**
     * Sets the value of the aifReportingObligationChangeFrequencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingObligationChangeFrequencyCodeType }
     *     
     */
    public void setAIFReportingObligationChangeFrequencyCode(ReportingObligationChangeFrequencyCodeType value) {
        this.aifReportingObligationChangeFrequencyCode = value;
    }

    /**
     * Gets the value of the aifReportingObligationChangeContentsCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAIFReportingObligationChangeContentsCode() {
        return aifReportingObligationChangeContentsCode;
    }

    /**
     * Sets the value of the aifReportingObligationChangeContentsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAIFReportingObligationChangeContentsCode(BigInteger value) {
        this.aifReportingObligationChangeContentsCode = value;
    }

    /**
     * Gets the value of the aifReportingObligationChangeQuarter property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingObligationChangeQuarterType }
     *     
     */
    public ReportingObligationChangeQuarterType getAIFReportingObligationChangeQuarter() {
        return aifReportingObligationChangeQuarter;
    }

    /**
     * Sets the value of the aifReportingObligationChangeQuarter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingObligationChangeQuarterType }
     *     
     */
    public void setAIFReportingObligationChangeQuarter(ReportingObligationChangeQuarterType value) {
        this.aifReportingObligationChangeQuarter = value;
    }

    /**
     * Gets the value of the lastReportingFlag property.
     * 
     */
    public boolean isLastReportingFlag() {
        return lastReportingFlag;
    }

    /**
     * Sets the value of the lastReportingFlag property.
     * 
     */
    public void setLastReportingFlag(boolean value) {
        this.lastReportingFlag = value;
    }

    /**
     * Gets the value of the assumptions property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAssumptionsType }
     *     
     */
    public ComplexAssumptionsType getAssumptions() {
        return assumptions;
    }

    /**
     * Sets the value of the assumptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAssumptionsType }
     *     
     */
    public void setAssumptions(ComplexAssumptionsType value) {
        this.assumptions = value;
    }

    /**
     * Gets the value of the aifmNationalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFMNationalCode() {
        return aifmNationalCode;
    }

    /**
     * Sets the value of the aifmNationalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFMNationalCode(String value) {
        this.aifmNationalCode = value;
    }

    /**
     * Gets the value of the aifNationalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFNationalCode() {
        return aifNationalCode;
    }

    /**
     * Sets the value of the aifNationalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFNationalCode(String value) {
        this.aifNationalCode = value;
    }

    /**
     * Gets the value of the aifName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFName() {
        return aifName;
    }

    /**
     * Sets the value of the aifName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFName(String value) {
        this.aifName = value;
    }

    /**
     * Gets the value of the aifeeaFlag property.
     * 
     */
    public boolean isAIFEEAFlag() {
        return aifeeaFlag;
    }

    /**
     * Sets the value of the aifeeaFlag property.
     * 
     */
    public void setAIFEEAFlag(boolean value) {
        this.aifeeaFlag = value;
    }

    /**
     * Gets the value of the aifReportingCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAIFReportingCode() {
        return aifReportingCode;
    }

    /**
     * Sets the value of the aifReportingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAIFReportingCode(BigInteger value) {
        this.aifReportingCode = value;
    }

    /**
     * Gets the value of the aifDomicile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFDomicile() {
        return aifDomicile;
    }

    /**
     * Sets the value of the aifDomicile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFDomicile(String value) {
        this.aifDomicile = value;
    }

    /**
     * Gets the value of the inceptionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInceptionDate() {
        return inceptionDate;
    }

    /**
     * Sets the value of the inceptionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInceptionDate(XMLGregorianCalendar value) {
        this.inceptionDate = value;
    }

    /**
     * Gets the value of the aifNoReportingFlag property.
     * 
     */
    public boolean isAIFNoReportingFlag() {
        return aifNoReportingFlag;
    }

    /**
     * Sets the value of the aifNoReportingFlag property.
     * 
     */
    public void setAIFNoReportingFlag(boolean value) {
        this.aifNoReportingFlag = value;
    }

    /**
     * Gets the value of the aifCompleteDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAIFCompleteDescriptionType }
     *     
     */
    public ComplexAIFCompleteDescriptionType getAIFCompleteDescription() {
        return aifCompleteDescription;
    }

    /**
     * Sets the value of the aifCompleteDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAIFCompleteDescriptionType }
     *     
     */
    public void setAIFCompleteDescription(ComplexAIFCompleteDescriptionType value) {
        this.aifCompleteDescription = value;
    }

}
