//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexMarketRate3p2Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexMarketRate3p2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegulatedMarketRate" type="{}UnsignedPercentType" minOccurs="0"/>
 *         &lt;element name="OTCRate" type="{}UnsignedPercentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexMarketRate3p2Type", propOrder = {
    "regulatedMarketRate",
    "otcRate"
})
public class ComplexMarketRate3P2Type {

    @XmlElement(name = "RegulatedMarketRate")
    protected BigDecimal regulatedMarketRate;
    @XmlElement(name = "OTCRate")
    protected BigDecimal otcRate;

    /**
     * Gets the value of the regulatedMarketRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRegulatedMarketRate() {
        return regulatedMarketRate;
    }

    /**
     * Sets the value of the regulatedMarketRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRegulatedMarketRate(BigDecimal value) {
        this.regulatedMarketRate = value;
    }

    /**
     * Gets the value of the otcRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOTCRate() {
        return otcRate;
    }

    /**
     * Sets the value of the otcRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOTCRate(BigDecimal value) {
        this.otcRate = value;
    }

}
