//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexAIFPrincipalInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexAIFPrincipalInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AIFIdentification" type="{}ComplexAIFIdentifierType" minOccurs="0"/>
 *         &lt;element name="ShareClassFlag" type="{}BooleanType"/>
 *         &lt;element name="ShareClassIdentification" type="{}ComplexShareClassIdentificationType" minOccurs="0"/>
 *         &lt;element name="AIFDescription" type="{}ComplexAIFDescriptionType"/>
 *         &lt;element name="MainInstrumentsTraded" type="{}ComplexMainInstrumentsTradedType"/>
 *         &lt;element name="NAVGeographicalFocus" type="{}ComplexNAVGeographicalFocusType"/>
 *         &lt;element name="AUMGeographicalFocus" type="{}ComplexAUMGeographicalFocusType" minOccurs="0"/>
 *         &lt;element name="PrincipalExposures" type="{}ComplexPrincipalExposuresType"/>
 *         &lt;element name="MostImportantConcentration" type="{}ComplexMostImportantConcentrationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexAIFPrincipalInfoType", propOrder = {
    "aifIdentification",
    "shareClassFlag",
    "shareClassIdentification",
    "aifDescription",
    "mainInstrumentsTraded",
    "navGeographicalFocus",
    "aumGeographicalFocus",
    "principalExposures",
    "mostImportantConcentration"
})
public class ComplexAIFPrincipalInfoType {

    @XmlElement(name = "AIFIdentification")
    protected ComplexAIFIdentifierType aifIdentification;
    @XmlElement(name = "ShareClassFlag")
    protected boolean shareClassFlag;
    @XmlElement(name = "ShareClassIdentification")
    protected ComplexShareClassIdentificationType shareClassIdentification;
    @XmlElement(name = "AIFDescription", required = true)
    protected ComplexAIFDescriptionType aifDescription;
    @XmlElement(name = "MainInstrumentsTraded", required = true)
    protected ComplexMainInstrumentsTradedType mainInstrumentsTraded;
    @XmlElement(name = "NAVGeographicalFocus", required = true)
    protected ComplexNAVGeographicalFocusType navGeographicalFocus;
    @XmlElement(name = "AUMGeographicalFocus")
    protected ComplexAUMGeographicalFocusType aumGeographicalFocus;
    @XmlElement(name = "PrincipalExposures", required = true)
    protected ComplexPrincipalExposuresType principalExposures;
    @XmlElement(name = "MostImportantConcentration", required = true)
    protected ComplexMostImportantConcentrationType mostImportantConcentration;

    /**
     * Gets the value of the aifIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAIFIdentifierType }
     *     
     */
    public ComplexAIFIdentifierType getAIFIdentification() {
        return aifIdentification;
    }

    /**
     * Sets the value of the aifIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAIFIdentifierType }
     *     
     */
    public void setAIFIdentification(ComplexAIFIdentifierType value) {
        this.aifIdentification = value;
    }

    /**
     * Gets the value of the shareClassFlag property.
     * 
     */
    public boolean isShareClassFlag() {
        return shareClassFlag;
    }

    /**
     * Sets the value of the shareClassFlag property.
     * 
     */
    public void setShareClassFlag(boolean value) {
        this.shareClassFlag = value;
    }

    /**
     * Gets the value of the shareClassIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexShareClassIdentificationType }
     *     
     */
    public ComplexShareClassIdentificationType getShareClassIdentification() {
        return shareClassIdentification;
    }

    /**
     * Sets the value of the shareClassIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexShareClassIdentificationType }
     *     
     */
    public void setShareClassIdentification(ComplexShareClassIdentificationType value) {
        this.shareClassIdentification = value;
    }

    /**
     * Gets the value of the aifDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAIFDescriptionType }
     *     
     */
    public ComplexAIFDescriptionType getAIFDescription() {
        return aifDescription;
    }

    /**
     * Sets the value of the aifDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAIFDescriptionType }
     *     
     */
    public void setAIFDescription(ComplexAIFDescriptionType value) {
        this.aifDescription = value;
    }

    /**
     * Gets the value of the mainInstrumentsTraded property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexMainInstrumentsTradedType }
     *     
     */
    public ComplexMainInstrumentsTradedType getMainInstrumentsTraded() {
        return mainInstrumentsTraded;
    }

    /**
     * Sets the value of the mainInstrumentsTraded property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexMainInstrumentsTradedType }
     *     
     */
    public void setMainInstrumentsTraded(ComplexMainInstrumentsTradedType value) {
        this.mainInstrumentsTraded = value;
    }

    /**
     * Gets the value of the navGeographicalFocus property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexNAVGeographicalFocusType }
     *     
     */
    public ComplexNAVGeographicalFocusType getNAVGeographicalFocus() {
        return navGeographicalFocus;
    }

    /**
     * Sets the value of the navGeographicalFocus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexNAVGeographicalFocusType }
     *     
     */
    public void setNAVGeographicalFocus(ComplexNAVGeographicalFocusType value) {
        this.navGeographicalFocus = value;
    }

    /**
     * Gets the value of the aumGeographicalFocus property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAUMGeographicalFocusType }
     *     
     */
    public ComplexAUMGeographicalFocusType getAUMGeographicalFocus() {
        return aumGeographicalFocus;
    }

    /**
     * Sets the value of the aumGeographicalFocus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAUMGeographicalFocusType }
     *     
     */
    public void setAUMGeographicalFocus(ComplexAUMGeographicalFocusType value) {
        this.aumGeographicalFocus = value;
    }

    /**
     * Gets the value of the principalExposures property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexPrincipalExposuresType }
     *     
     */
    public ComplexPrincipalExposuresType getPrincipalExposures() {
        return principalExposures;
    }

    /**
     * Sets the value of the principalExposures property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexPrincipalExposuresType }
     *     
     */
    public void setPrincipalExposures(ComplexPrincipalExposuresType value) {
        this.principalExposures = value;
    }

    /**
     * Gets the value of the mostImportantConcentration property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexMostImportantConcentrationType }
     *     
     */
    public ComplexMostImportantConcentrationType getMostImportantConcentration() {
        return mostImportantConcentration;
    }

    /**
     * Sets the value of the mostImportantConcentration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexMostImportantConcentrationType }
     *     
     */
    public void setMostImportantConcentration(ComplexMostImportantConcentrationType value) {
        this.mostImportantConcentration = value;
    }

}
