//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexPrincipalExposureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexPrincipalExposureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ranking" type="{}TenRankingType"/>
 *         &lt;element name="AssetMacroType" type="{}AssetMacroTypeType"/>
 *         &lt;element name="SubAssetType" type="{}SubAssetTypeType" minOccurs="0"/>
 *         &lt;element name="PositionType" type="{}PositionTypeType" minOccurs="0"/>
 *         &lt;element name="AggregatedValueAmount" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *         &lt;element name="AggregatedValueRate" type="{}UnsignedPercentType" minOccurs="0"/>
 *         &lt;element name="CounterpartyIdentification" type="{}ComplexEntityIdentificationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexPrincipalExposureType", propOrder = {
    "ranking",
    "assetMacroType",
    "subAssetType",
    "positionType",
    "aggregatedValueAmount",
    "aggregatedValueRate",
    "counterpartyIdentification"
})
public class ComplexPrincipalExposureType {

    @XmlElement(name = "Ranking", required = true)
    protected BigInteger ranking;
    @XmlElement(name = "AssetMacroType", required = true)
    protected AssetMacroTypeType assetMacroType;
    @XmlElement(name = "SubAssetType")
    protected SubAssetTypeType subAssetType;
    @XmlElement(name = "PositionType")
    protected PositionTypeType positionType;
    @XmlElement(name = "AggregatedValueAmount")
    protected BigInteger aggregatedValueAmount;
    @XmlElement(name = "AggregatedValueRate")
    protected BigDecimal aggregatedValueRate;
    @XmlElement(name = "CounterpartyIdentification")
    protected ComplexEntityIdentificationType counterpartyIdentification;

    /**
     * Gets the value of the ranking property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRanking() {
        return ranking;
    }

    /**
     * Sets the value of the ranking property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRanking(BigInteger value) {
        this.ranking = value;
    }

    /**
     * Gets the value of the assetMacroType property.
     * 
     * @return
     *     possible object is
     *     {@link AssetMacroTypeType }
     *     
     */
    public AssetMacroTypeType getAssetMacroType() {
        return assetMacroType;
    }

    /**
     * Sets the value of the assetMacroType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetMacroTypeType }
     *     
     */
    public void setAssetMacroType(AssetMacroTypeType value) {
        this.assetMacroType = value;
    }

    /**
     * Gets the value of the subAssetType property.
     * 
     * @return
     *     possible object is
     *     {@link SubAssetTypeType }
     *     
     */
    public SubAssetTypeType getSubAssetType() {
        return subAssetType;
    }

    /**
     * Sets the value of the subAssetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubAssetTypeType }
     *     
     */
    public void setSubAssetType(SubAssetTypeType value) {
        this.subAssetType = value;
    }

    /**
     * Gets the value of the positionType property.
     * 
     * @return
     *     possible object is
     *     {@link PositionTypeType }
     *     
     */
    public PositionTypeType getPositionType() {
        return positionType;
    }

    /**
     * Sets the value of the positionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionTypeType }
     *     
     */
    public void setPositionType(PositionTypeType value) {
        this.positionType = value;
    }

    /**
     * Gets the value of the aggregatedValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAggregatedValueAmount() {
        return aggregatedValueAmount;
    }

    /**
     * Sets the value of the aggregatedValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAggregatedValueAmount(BigInteger value) {
        this.aggregatedValueAmount = value;
    }

    /**
     * Gets the value of the aggregatedValueRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAggregatedValueRate() {
        return aggregatedValueRate;
    }

    /**
     * Sets the value of the aggregatedValueRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAggregatedValueRate(BigDecimal value) {
        this.aggregatedValueRate = value;
    }

    /**
     * Gets the value of the counterpartyIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public ComplexEntityIdentificationType getCounterpartyIdentification() {
        return counterpartyIdentification;
    }

    /**
     * Sets the value of the counterpartyIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public void setCounterpartyIdentification(ComplexEntityIdentificationType value) {
        this.counterpartyIdentification = value;
    }

}
