//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexLeverageAIFType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexLeverageAIFType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrossMethodRate" type="{}SignedRate15p2Type"/>
 *         &lt;element name="CommitmentMethodRate" type="{}SignedRate15p2Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexLeverageAIFType", propOrder = {
    "grossMethodRate",
    "commitmentMethodRate"
})
public class ComplexLeverageAIFType {

    @XmlElement(name = "GrossMethodRate", required = true)
    protected BigDecimal grossMethodRate;
    @XmlElement(name = "CommitmentMethodRate", required = true)
    protected BigDecimal commitmentMethodRate;

    /**
     * Gets the value of the grossMethodRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossMethodRate() {
        return grossMethodRate;
    }

    /**
     * Sets the value of the grossMethodRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossMethodRate(BigDecimal value) {
        this.grossMethodRate = value;
    }

    /**
     * Gets the value of the commitmentMethodRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCommitmentMethodRate() {
        return commitmentMethodRate;
    }

    /**
     * Sets the value of the commitmentMethodRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCommitmentMethodRate(BigDecimal value) {
        this.commitmentMethodRate = value;
    }

}
