//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexAIFMNationalIdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexAIFMNationalIdentifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportingMemberState" type="{}CountryCodeType"/>
 *         &lt;element name="AIFMNationalCode" type="{}AIFMNationalCodeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexAIFMNationalIdentifierType", propOrder = {
    "reportingMemberState",
    "aifmNationalCode"
})
public class ComplexAIFMNationalIdentifierType {

    @XmlElement(name = "ReportingMemberState", required = true)
    protected String reportingMemberState;
    @XmlElement(name = "AIFMNationalCode", required = true)
    protected String aifmNationalCode;

    /**
     * Gets the value of the reportingMemberState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingMemberState() {
        return reportingMemberState;
    }

    /**
     * Sets the value of the reportingMemberState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingMemberState(String value) {
        this.reportingMemberState = value;
    }

    /**
     * Gets the value of the aifmNationalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFMNationalCode() {
        return aifmNationalCode;
    }

    /**
     * Sets the value of the aifmNationalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFMNationalCode(String value) {
        this.aifmNationalCode = value;
    }

}
