//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexCompanyDominantInfluenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexCompanyDominantInfluenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompanyIdentification" type="{}ComplexEntityIdentificationType"/>
 *         &lt;element name="TransactionType" type="{}TransactionTypeType"/>
 *         &lt;element name="OtherTransactionTypeDescription" type="{}StringRestricted300Type" minOccurs="0"/>
 *         &lt;element name="VotingRightsRate" type="{}UnsignedPercentType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexCompanyDominantInfluenceType", propOrder = {
    "companyIdentification",
    "transactionType",
    "otherTransactionTypeDescription",
    "votingRightsRate"
})
public class ComplexCompanyDominantInfluenceType {

    @XmlElement(name = "CompanyIdentification", required = true)
    protected ComplexEntityIdentificationType companyIdentification;
    @XmlElement(name = "TransactionType", required = true)
    protected TransactionTypeType transactionType;
    @XmlElement(name = "OtherTransactionTypeDescription")
    protected String otherTransactionTypeDescription;
    @XmlElement(name = "VotingRightsRate", required = true)
    protected BigDecimal votingRightsRate;

    /**
     * Gets the value of the companyIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public ComplexEntityIdentificationType getCompanyIdentification() {
        return companyIdentification;
    }

    /**
     * Sets the value of the companyIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public void setCompanyIdentification(ComplexEntityIdentificationType value) {
        this.companyIdentification = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionTypeType }
     *     
     */
    public TransactionTypeType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionTypeType }
     *     
     */
    public void setTransactionType(TransactionTypeType value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the otherTransactionTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherTransactionTypeDescription() {
        return otherTransactionTypeDescription;
    }

    /**
     * Sets the value of the otherTransactionTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherTransactionTypeDescription(String value) {
        this.otherTransactionTypeDescription = value;
    }

    /**
     * Gets the value of the votingRightsRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVotingRightsRate() {
        return votingRightsRate;
    }

    /**
     * Sets the value of the votingRightsRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVotingRightsRate(BigDecimal value) {
        this.votingRightsRate = value;
    }

}
