//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexBorrowingSourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexBorrowingSourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ranking" type="{}FiveRankingType"/>
 *         &lt;element name="BorrowingSourceFlag" type="{}BooleanType"/>
 *         &lt;element name="SourceIdentification" type="{}ComplexEntityIdentificationType" minOccurs="0"/>
 *         &lt;element name="LeverageAmount" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexBorrowingSourceType", propOrder = {
    "ranking",
    "borrowingSourceFlag",
    "sourceIdentification",
    "leverageAmount"
})
public class ComplexBorrowingSourceType {

    @XmlElement(name = "Ranking", required = true)
    protected BigInteger ranking;
    @XmlElement(name = "BorrowingSourceFlag")
    protected boolean borrowingSourceFlag;
    @XmlElement(name = "SourceIdentification")
    protected ComplexEntityIdentificationType sourceIdentification;
    @XmlElement(name = "LeverageAmount")
    protected BigInteger leverageAmount;

    /**
     * Gets the value of the ranking property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRanking() {
        return ranking;
    }

    /**
     * Sets the value of the ranking property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRanking(BigInteger value) {
        this.ranking = value;
    }

    /**
     * Gets the value of the borrowingSourceFlag property.
     * 
     */
    public boolean isBorrowingSourceFlag() {
        return borrowingSourceFlag;
    }

    /**
     * Sets the value of the borrowingSourceFlag property.
     * 
     */
    public void setBorrowingSourceFlag(boolean value) {
        this.borrowingSourceFlag = value;
    }

    /**
     * Gets the value of the sourceIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public ComplexEntityIdentificationType getSourceIdentification() {
        return sourceIdentification;
    }

    /**
     * Sets the value of the sourceIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public void setSourceIdentification(ComplexEntityIdentificationType value) {
        this.sourceIdentification = value;
    }

    /**
     * Gets the value of the leverageAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeverageAmount() {
        return leverageAmount;
    }

    /**
     * Sets the value of the leverageAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeverageAmount(BigInteger value) {
        this.leverageAmount = value;
    }

}
