//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexMarketIdentificationWithoutNOTType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexMarketIdentificationWithoutNOTType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarketCodeType" type="{}MarketCodeTypeWithoutNOTType"/>
 *         &lt;element name="MarketCode" type="{}MICCodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexMarketIdentificationWithoutNOTType", propOrder = {
    "marketCodeType",
    "marketCode"
})
public class ComplexMarketIdentificationWithoutNOTType {

    @XmlElement(name = "MarketCodeType", required = true)
    protected MarketCodeTypeWithoutNOTType marketCodeType;
    @XmlElement(name = "MarketCode")
    protected String marketCode;

    /**
     * Gets the value of the marketCodeType property.
     * 
     * @return
     *     possible object is
     *     {@link MarketCodeTypeWithoutNOTType }
     *     
     */
    public MarketCodeTypeWithoutNOTType getMarketCodeType() {
        return marketCodeType;
    }

    /**
     * Sets the value of the marketCodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketCodeTypeWithoutNOTType }
     *     
     */
    public void setMarketCodeType(MarketCodeTypeWithoutNOTType value) {
        this.marketCodeType = value;
    }

    /**
     * Gets the value of the marketCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketCode() {
        return marketCode;
    }

    /**
     * Sets the value of the marketCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketCode(String value) {
        this.marketCode = value;
    }

}
