//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexAllCounterpartyCollateralType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexAllCounterpartyCollateralType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AllCounterpartyCollateralCash" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *         &lt;element name="AllCounterpartyCollateralSecurities" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *         &lt;element name="AllCounterpartyOtherCollateralPosted" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexAllCounterpartyCollateralType", propOrder = {
    "allCounterpartyCollateralCash",
    "allCounterpartyCollateralSecurities",
    "allCounterpartyOtherCollateralPosted"
})
public class ComplexAllCounterpartyCollateralType {

    @XmlElement(name = "AllCounterpartyCollateralCash")
    protected BigInteger allCounterpartyCollateralCash;
    @XmlElement(name = "AllCounterpartyCollateralSecurities")
    protected BigInteger allCounterpartyCollateralSecurities;
    @XmlElement(name = "AllCounterpartyOtherCollateralPosted")
    protected BigInteger allCounterpartyOtherCollateralPosted;

    /**
     * Gets the value of the allCounterpartyCollateralCash property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllCounterpartyCollateralCash() {
        return allCounterpartyCollateralCash;
    }

    /**
     * Sets the value of the allCounterpartyCollateralCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllCounterpartyCollateralCash(BigInteger value) {
        this.allCounterpartyCollateralCash = value;
    }

    /**
     * Gets the value of the allCounterpartyCollateralSecurities property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllCounterpartyCollateralSecurities() {
        return allCounterpartyCollateralSecurities;
    }

    /**
     * Sets the value of the allCounterpartyCollateralSecurities property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllCounterpartyCollateralSecurities(BigInteger value) {
        this.allCounterpartyCollateralSecurities = value;
    }

    /**
     * Gets the value of the allCounterpartyOtherCollateralPosted property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllCounterpartyOtherCollateralPosted() {
        return allCounterpartyOtherCollateralPosted;
    }

    /**
     * Sets the value of the allCounterpartyOtherCollateralPosted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllCounterpartyOtherCollateralPosted(BigInteger value) {
        this.allCounterpartyOtherCollateralPosted = value;
    }

}
