//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexFundOfFundsStrategyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexFundOfFundsStrategyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FundOfFundsStrategyType" type="{}FundOfFundsStrategyTypeType"/>
 *         &lt;element name="PrimaryStrategyFlag" type="{}BooleanType"/>
 *         &lt;element name="StrategyNAVRate" type="{}SignedRate15p2Type" minOccurs="0"/>
 *         &lt;element name="StrategyTypeOtherDescription" type="{}StringRestricted300Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexFundOfFundsStrategyType", propOrder = {
    "fundOfFundsStrategyType",
    "primaryStrategyFlag",
    "strategyNAVRate",
    "strategyTypeOtherDescription"
})
public class ComplexFundOfFundsStrategyType {

    @XmlElement(name = "FundOfFundsStrategyType", required = true)
    protected FundOfFundsStrategyTypeType fundOfFundsStrategyType;
    @XmlElement(name = "PrimaryStrategyFlag")
    protected boolean primaryStrategyFlag;
    @XmlElement(name = "StrategyNAVRate")
    protected BigDecimal strategyNAVRate;
    @XmlElement(name = "StrategyTypeOtherDescription")
    protected String strategyTypeOtherDescription;

    /**
     * Gets the value of the fundOfFundsStrategyType property.
     * 
     * @return
     *     possible object is
     *     {@link FundOfFundsStrategyTypeType }
     *     
     */
    public FundOfFundsStrategyTypeType getFundOfFundsStrategyType() {
        return fundOfFundsStrategyType;
    }

    /**
     * Sets the value of the fundOfFundsStrategyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundOfFundsStrategyTypeType }
     *     
     */
    public void setFundOfFundsStrategyType(FundOfFundsStrategyTypeType value) {
        this.fundOfFundsStrategyType = value;
    }

    /**
     * Gets the value of the primaryStrategyFlag property.
     * 
     */
    public boolean isPrimaryStrategyFlag() {
        return primaryStrategyFlag;
    }

    /**
     * Sets the value of the primaryStrategyFlag property.
     * 
     */
    public void setPrimaryStrategyFlag(boolean value) {
        this.primaryStrategyFlag = value;
    }

    /**
     * Gets the value of the strategyNAVRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStrategyNAVRate() {
        return strategyNAVRate;
    }

    /**
     * Sets the value of the strategyNAVRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStrategyNAVRate(BigDecimal value) {
        this.strategyNAVRate = value;
    }

    /**
     * Gets the value of the strategyTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrategyTypeOtherDescription() {
        return strategyTypeOtherDescription;
    }

    /**
     * Sets the value of the strategyTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrategyTypeOtherDescription(String value) {
        this.strategyTypeOtherDescription = value;
    }

}
