//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ComplexAIIInstrumentIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexAIIInstrumentIdentificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AIIExchangeCode" type="{}MICCodeType"/>
 *         &lt;element name="AIIProductCode" type="{}AIIProductCodeType"/>
 *         &lt;element name="AIIDerivativeType" type="{}AIIDerivativeTypeType"/>
 *         &lt;element name="AIIPutCallIdentifier" type="{}AIIPutCallIdentifierType"/>
 *         &lt;element name="AIIExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="AIIStrikePrice" type="{}UnsignedDecimal15p4Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexAIIInstrumentIdentificationType", propOrder = {
    "aiiExchangeCode",
    "aiiProductCode",
    "aiiDerivativeType",
    "aiiPutCallIdentifier",
    "aiiExpiryDate",
    "aiiStrikePrice"
})
public class ComplexAIIInstrumentIdentificationType {

    @XmlElement(name = "AIIExchangeCode", required = true)
    protected String aiiExchangeCode;
    @XmlElement(name = "AIIProductCode", required = true)
    protected String aiiProductCode;
    @XmlElement(name = "AIIDerivativeType", required = true)
    protected AIIDerivativeTypeType aiiDerivativeType;
    @XmlElement(name = "AIIPutCallIdentifier", required = true)
    protected AIIPutCallIdentifierType aiiPutCallIdentifier;
    @XmlElement(name = "AIIExpiryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar aiiExpiryDate;
    @XmlElement(name = "AIIStrikePrice", required = true)
    protected BigDecimal aiiStrikePrice;

    /**
     * Gets the value of the aiiExchangeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIIExchangeCode() {
        return aiiExchangeCode;
    }

    /**
     * Sets the value of the aiiExchangeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIIExchangeCode(String value) {
        this.aiiExchangeCode = value;
    }

    /**
     * Gets the value of the aiiProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIIProductCode() {
        return aiiProductCode;
    }

    /**
     * Sets the value of the aiiProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIIProductCode(String value) {
        this.aiiProductCode = value;
    }

    /**
     * Gets the value of the aiiDerivativeType property.
     * 
     * @return
     *     possible object is
     *     {@link AIIDerivativeTypeType }
     *     
     */
    public AIIDerivativeTypeType getAIIDerivativeType() {
        return aiiDerivativeType;
    }

    /**
     * Sets the value of the aiiDerivativeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AIIDerivativeTypeType }
     *     
     */
    public void setAIIDerivativeType(AIIDerivativeTypeType value) {
        this.aiiDerivativeType = value;
    }

    /**
     * Gets the value of the aiiPutCallIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link AIIPutCallIdentifierType }
     *     
     */
    public AIIPutCallIdentifierType getAIIPutCallIdentifier() {
        return aiiPutCallIdentifier;
    }

    /**
     * Sets the value of the aiiPutCallIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link AIIPutCallIdentifierType }
     *     
     */
    public void setAIIPutCallIdentifier(AIIPutCallIdentifierType value) {
        this.aiiPutCallIdentifier = value;
    }

    /**
     * Gets the value of the aiiExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAIIExpiryDate() {
        return aiiExpiryDate;
    }

    /**
     * Sets the value of the aiiExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAIIExpiryDate(XMLGregorianCalendar value) {
        this.aiiExpiryDate = value;
    }

    /**
     * Gets the value of the aiiStrikePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAIIStrikePrice() {
        return aiiStrikePrice;
    }

    /**
     * Sets the value of the aiiStrikePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAIIStrikePrice(BigDecimal value) {
        this.aiiStrikePrice = value;
    }

}
