//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexCounterpartyExposureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexCounterpartyExposureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ranking" type="{}FiveRankingType"/>
 *         &lt;element name="CounterpartyExposureFlag" type="{}BooleanType"/>
 *         &lt;element name="CounterpartyIdentification" type="{}ComplexEntityIdentificationType" minOccurs="0"/>
 *         &lt;element name="CounterpartyTotalExposureRate" type="{}UnsignedDecimal15p4Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexCounterpartyExposureType", propOrder = {
    "ranking",
    "counterpartyExposureFlag",
    "counterpartyIdentification",
    "counterpartyTotalExposureRate"
})
public class ComplexCounterpartyExposureType {

    @XmlElement(name = "Ranking", required = true)
    protected BigInteger ranking;
    @XmlElement(name = "CounterpartyExposureFlag")
    protected boolean counterpartyExposureFlag;
    @XmlElement(name = "CounterpartyIdentification")
    protected ComplexEntityIdentificationType counterpartyIdentification;
    @XmlElement(name = "CounterpartyTotalExposureRate")
    protected BigDecimal counterpartyTotalExposureRate;

    /**
     * Gets the value of the ranking property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRanking() {
        return ranking;
    }

    /**
     * Sets the value of the ranking property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRanking(BigInteger value) {
        this.ranking = value;
    }

    /**
     * Gets the value of the counterpartyExposureFlag property.
     * 
     */
    public boolean isCounterpartyExposureFlag() {
        return counterpartyExposureFlag;
    }

    /**
     * Sets the value of the counterpartyExposureFlag property.
     * 
     */
    public void setCounterpartyExposureFlag(boolean value) {
        this.counterpartyExposureFlag = value;
    }

    /**
     * Gets the value of the counterpartyIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public ComplexEntityIdentificationType getCounterpartyIdentification() {
        return counterpartyIdentification;
    }

    /**
     * Sets the value of the counterpartyIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public void setCounterpartyIdentification(ComplexEntityIdentificationType value) {
        this.counterpartyIdentification = value;
    }

    /**
     * Gets the value of the counterpartyTotalExposureRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCounterpartyTotalExposureRate() {
        return counterpartyTotalExposureRate;
    }

    /**
     * Sets the value of the counterpartyTotalExposureRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCounterpartyTotalExposureRate(BigDecimal value) {
        this.counterpartyTotalExposureRate = value;
    }

}
