//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexVegaRiskMeasureValuesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexVegaRiskMeasureValuesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CurrentMarketRiskMeasureValue" type="{}SignedRate15p2Type" minOccurs="0"/>
 *         &lt;element name="LowerMarketRiskMeasureValue" type="{}SignedRate15p2Type" minOccurs="0"/>
 *         &lt;element name="HigherMarketRiskMeasureValue" type="{}SignedRate15p2Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexVegaRiskMeasureValuesType", propOrder = {
    "currentMarketRiskMeasureValue",
    "lowerMarketRiskMeasureValue",
    "higherMarketRiskMeasureValue"
})
public class ComplexVegaRiskMeasureValuesType {

    @XmlElement(name = "CurrentMarketRiskMeasureValue")
    protected BigDecimal currentMarketRiskMeasureValue;
    @XmlElement(name = "LowerMarketRiskMeasureValue")
    protected BigDecimal lowerMarketRiskMeasureValue;
    @XmlElement(name = "HigherMarketRiskMeasureValue")
    protected BigDecimal higherMarketRiskMeasureValue;

    /**
     * Gets the value of the currentMarketRiskMeasureValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentMarketRiskMeasureValue() {
        return currentMarketRiskMeasureValue;
    }

    /**
     * Sets the value of the currentMarketRiskMeasureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentMarketRiskMeasureValue(BigDecimal value) {
        this.currentMarketRiskMeasureValue = value;
    }

    /**
     * Gets the value of the lowerMarketRiskMeasureValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLowerMarketRiskMeasureValue() {
        return lowerMarketRiskMeasureValue;
    }

    /**
     * Sets the value of the lowerMarketRiskMeasureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLowerMarketRiskMeasureValue(BigDecimal value) {
        this.lowerMarketRiskMeasureValue = value;
    }

    /**
     * Gets the value of the higherMarketRiskMeasureValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHigherMarketRiskMeasureValue() {
        return higherMarketRiskMeasureValue;
    }

    /**
     * Sets the value of the higherMarketRiskMeasureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHigherMarketRiskMeasureValue(BigDecimal value) {
        this.higherMarketRiskMeasureValue = value;
    }

}
