//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexBaseCurrencyDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexBaseCurrencyDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BaseCurrency" type="{}CurrencyCodeType"/>
 *         &lt;element name="AUMAmountInBaseCurrency" type="{}UnsignedInteger15pType"/>
 *         &lt;element name="FXEURReferenceRateType" type="{}FXEURReferenceRateTypeType" minOccurs="0"/>
 *         &lt;element name="FXEURRate" type="{}UnsignedDecimal15p4Type" minOccurs="0"/>
 *         &lt;element name="FXEUROtherReferenceRateDescription" type="{}StringRestricted30Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexBaseCurrencyDescriptionType", propOrder = {
    "baseCurrency",
    "aumAmountInBaseCurrency",
    "fxeurReferenceRateType",
    "fxeurRate",
    "fxeurOtherReferenceRateDescription"
})
public class ComplexBaseCurrencyDescriptionType {

    @XmlElement(name = "BaseCurrency", required = true)
    protected String baseCurrency;
    @XmlElement(name = "AUMAmountInBaseCurrency", required = true)
    protected BigInteger aumAmountInBaseCurrency;
    @XmlElement(name = "FXEURReferenceRateType")
    protected FXEURReferenceRateTypeType fxeurReferenceRateType;
    @XmlElement(name = "FXEURRate")
    protected BigDecimal fxeurRate;
    @XmlElement(name = "FXEUROtherReferenceRateDescription")
    protected String fxeurOtherReferenceRateDescription;

    /**
     * Gets the value of the baseCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCurrency() {
        return baseCurrency;
    }

    /**
     * Sets the value of the baseCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCurrency(String value) {
        this.baseCurrency = value;
    }

    /**
     * Gets the value of the aumAmountInBaseCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAUMAmountInBaseCurrency() {
        return aumAmountInBaseCurrency;
    }

    /**
     * Sets the value of the aumAmountInBaseCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAUMAmountInBaseCurrency(BigInteger value) {
        this.aumAmountInBaseCurrency = value;
    }

    /**
     * Gets the value of the fxeurReferenceRateType property.
     * 
     * @return
     *     possible object is
     *     {@link FXEURReferenceRateTypeType }
     *     
     */
    public FXEURReferenceRateTypeType getFXEURReferenceRateType() {
        return fxeurReferenceRateType;
    }

    /**
     * Sets the value of the fxeurReferenceRateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FXEURReferenceRateTypeType }
     *     
     */
    public void setFXEURReferenceRateType(FXEURReferenceRateTypeType value) {
        this.fxeurReferenceRateType = value;
    }

    /**
     * Gets the value of the fxeurRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFXEURRate() {
        return fxeurRate;
    }

    /**
     * Sets the value of the fxeurRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFXEURRate(BigDecimal value) {
        this.fxeurRate = value;
    }

    /**
     * Gets the value of the fxeurOtherReferenceRateDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFXEUROtherReferenceRateDescription() {
        return fxeurOtherReferenceRateDescription;
    }

    /**
     * Sets the value of the fxeurOtherReferenceRateDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFXEUROtherReferenceRateDescription(String value) {
        this.fxeurOtherReferenceRateDescription = value;
    }

}
