//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexInvestorPreferentialTreatmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexInvestorPreferentialTreatmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvestorPreferentialTreatmentFlag" type="{}BooleanType"/>
 *         &lt;element name="DisclosureTermsPreferentialTreatmentFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="LiquidityTermsPreferentialTreatmentFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="FeeTermsPreferentialTreatmentFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="OtherTermsPreferentialTreatmentFlag" type="{}BooleanType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexInvestorPreferentialTreatmentType", propOrder = {
    "investorPreferentialTreatmentFlag",
    "disclosureTermsPreferentialTreatmentFlag",
    "liquidityTermsPreferentialTreatmentFlag",
    "feeTermsPreferentialTreatmentFlag",
    "otherTermsPreferentialTreatmentFlag"
})
public class ComplexInvestorPreferentialTreatmentType {

    @XmlElement(name = "InvestorPreferentialTreatmentFlag")
    protected boolean investorPreferentialTreatmentFlag;
    @XmlElement(name = "DisclosureTermsPreferentialTreatmentFlag")
    protected Boolean disclosureTermsPreferentialTreatmentFlag;
    @XmlElement(name = "LiquidityTermsPreferentialTreatmentFlag")
    protected Boolean liquidityTermsPreferentialTreatmentFlag;
    @XmlElement(name = "FeeTermsPreferentialTreatmentFlag")
    protected Boolean feeTermsPreferentialTreatmentFlag;
    @XmlElement(name = "OtherTermsPreferentialTreatmentFlag")
    protected Boolean otherTermsPreferentialTreatmentFlag;

    /**
     * Gets the value of the investorPreferentialTreatmentFlag property.
     * 
     */
    public boolean isInvestorPreferentialTreatmentFlag() {
        return investorPreferentialTreatmentFlag;
    }

    /**
     * Sets the value of the investorPreferentialTreatmentFlag property.
     * 
     */
    public void setInvestorPreferentialTreatmentFlag(boolean value) {
        this.investorPreferentialTreatmentFlag = value;
    }

    /**
     * Gets the value of the disclosureTermsPreferentialTreatmentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisclosureTermsPreferentialTreatmentFlag() {
        return disclosureTermsPreferentialTreatmentFlag;
    }

    /**
     * Sets the value of the disclosureTermsPreferentialTreatmentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisclosureTermsPreferentialTreatmentFlag(Boolean value) {
        this.disclosureTermsPreferentialTreatmentFlag = value;
    }

    /**
     * Gets the value of the liquidityTermsPreferentialTreatmentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLiquidityTermsPreferentialTreatmentFlag() {
        return liquidityTermsPreferentialTreatmentFlag;
    }

    /**
     * Sets the value of the liquidityTermsPreferentialTreatmentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLiquidityTermsPreferentialTreatmentFlag(Boolean value) {
        this.liquidityTermsPreferentialTreatmentFlag = value;
    }

    /**
     * Gets the value of the feeTermsPreferentialTreatmentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFeeTermsPreferentialTreatmentFlag() {
        return feeTermsPreferentialTreatmentFlag;
    }

    /**
     * Sets the value of the feeTermsPreferentialTreatmentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFeeTermsPreferentialTreatmentFlag(Boolean value) {
        this.feeTermsPreferentialTreatmentFlag = value;
    }

    /**
     * Gets the value of the otherTermsPreferentialTreatmentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOtherTermsPreferentialTreatmentFlag() {
        return otherTermsPreferentialTreatmentFlag;
    }

    /**
     * Sets the value of the otherTermsPreferentialTreatmentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOtherTermsPreferentialTreatmentFlag(Boolean value) {
        this.otherTermsPreferentialTreatmentFlag = value;
    }

}
