//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexInvestorRedemptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexInvestorRedemptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProvideWithdrawalRightsFlag" type="{}BooleanType"/>
 *         &lt;element name="InvestorRedemptionFrequency" type="{}InvestorRedemptionFrequencyType" minOccurs="0"/>
 *         &lt;element name="InvestorRedemptionNoticePeriod" type="{}UnsignedInteger4pType" minOccurs="0"/>
 *         &lt;element name="InvestorRedemptionLockUpPeriod" type="{}UnsignedInteger4pType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexInvestorRedemptionType", propOrder = {
    "provideWithdrawalRightsFlag",
    "investorRedemptionFrequency",
    "investorRedemptionNoticePeriod",
    "investorRedemptionLockUpPeriod"
})
public class ComplexInvestorRedemptionType {

    @XmlElement(name = "ProvideWithdrawalRightsFlag")
    protected boolean provideWithdrawalRightsFlag;
    @XmlElement(name = "InvestorRedemptionFrequency")
    protected InvestorRedemptionFrequencyType investorRedemptionFrequency;
    @XmlElement(name = "InvestorRedemptionNoticePeriod")
    protected BigInteger investorRedemptionNoticePeriod;
    @XmlElement(name = "InvestorRedemptionLockUpPeriod")
    protected BigInteger investorRedemptionLockUpPeriod;

    /**
     * Gets the value of the provideWithdrawalRightsFlag property.
     * 
     */
    public boolean isProvideWithdrawalRightsFlag() {
        return provideWithdrawalRightsFlag;
    }

    /**
     * Sets the value of the provideWithdrawalRightsFlag property.
     * 
     */
    public void setProvideWithdrawalRightsFlag(boolean value) {
        this.provideWithdrawalRightsFlag = value;
    }

    /**
     * Gets the value of the investorRedemptionFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link InvestorRedemptionFrequencyType }
     *     
     */
    public InvestorRedemptionFrequencyType getInvestorRedemptionFrequency() {
        return investorRedemptionFrequency;
    }

    /**
     * Sets the value of the investorRedemptionFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestorRedemptionFrequencyType }
     *     
     */
    public void setInvestorRedemptionFrequency(InvestorRedemptionFrequencyType value) {
        this.investorRedemptionFrequency = value;
    }

    /**
     * Gets the value of the investorRedemptionNoticePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInvestorRedemptionNoticePeriod() {
        return investorRedemptionNoticePeriod;
    }

    /**
     * Sets the value of the investorRedemptionNoticePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInvestorRedemptionNoticePeriod(BigInteger value) {
        this.investorRedemptionNoticePeriod = value;
    }

    /**
     * Gets the value of the investorRedemptionLockUpPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInvestorRedemptionLockUpPeriod() {
        return investorRedemptionLockUpPeriod;
    }

    /**
     * Sets the value of the investorRedemptionLockUpPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInvestorRedemptionLockUpPeriod(BigInteger value) {
        this.investorRedemptionLockUpPeriod = value;
    }

}
