//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexRiskProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexRiskProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarketRiskProfile" type="{}ComplexMarketRiskProfileType"/>
 *         &lt;element name="CounterpartyRiskProfile" type="{}ComplexCounterpartyRiskProfileType" minOccurs="0"/>
 *         &lt;element name="LiquidityRiskProfile" type="{}ComplexLiquidityRiskProfileType" minOccurs="0"/>
 *         &lt;element name="OperationalRisk" type="{}ComplexOperationalRiskType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexRiskProfileType", propOrder = {
    "marketRiskProfile",
    "counterpartyRiskProfile",
    "liquidityRiskProfile",
    "operationalRisk"
})
public class ComplexRiskProfileType {

    @XmlElement(name = "MarketRiskProfile", required = true)
    protected ComplexMarketRiskProfileType marketRiskProfile;
    @XmlElement(name = "CounterpartyRiskProfile")
    protected ComplexCounterpartyRiskProfileType counterpartyRiskProfile;
    @XmlElement(name = "LiquidityRiskProfile")
    protected ComplexLiquidityRiskProfileType liquidityRiskProfile;
    @XmlElement(name = "OperationalRisk")
    protected ComplexOperationalRiskType operationalRisk;

    /**
     * Gets the value of the marketRiskProfile property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexMarketRiskProfileType }
     *     
     */
    public ComplexMarketRiskProfileType getMarketRiskProfile() {
        return marketRiskProfile;
    }

    /**
     * Sets the value of the marketRiskProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexMarketRiskProfileType }
     *     
     */
    public void setMarketRiskProfile(ComplexMarketRiskProfileType value) {
        this.marketRiskProfile = value;
    }

    /**
     * Gets the value of the counterpartyRiskProfile property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexCounterpartyRiskProfileType }
     *     
     */
    public ComplexCounterpartyRiskProfileType getCounterpartyRiskProfile() {
        return counterpartyRiskProfile;
    }

    /**
     * Sets the value of the counterpartyRiskProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexCounterpartyRiskProfileType }
     *     
     */
    public void setCounterpartyRiskProfile(ComplexCounterpartyRiskProfileType value) {
        this.counterpartyRiskProfile = value;
    }

    /**
     * Gets the value of the liquidityRiskProfile property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexLiquidityRiskProfileType }
     *     
     */
    public ComplexLiquidityRiskProfileType getLiquidityRiskProfile() {
        return liquidityRiskProfile;
    }

    /**
     * Sets the value of the liquidityRiskProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexLiquidityRiskProfileType }
     *     
     */
    public void setLiquidityRiskProfile(ComplexLiquidityRiskProfileType value) {
        this.liquidityRiskProfile = value;
    }

    /**
     * Gets the value of the operationalRisk property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexOperationalRiskType }
     *     
     */
    public ComplexOperationalRiskType getOperationalRisk() {
        return operationalRisk;
    }

    /**
     * Sets the value of the operationalRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexOperationalRiskType }
     *     
     */
    public void setOperationalRisk(ComplexOperationalRiskType value) {
        this.operationalRisk = value;
    }

}
