//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexControlledStructureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexControlledStructureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ControlledStructureIdentification" type="{}ComplexEntityIdentificationType"/>
 *         &lt;element name="ControlledStructureExposureValue" type="{}UnsignedInteger15pType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexControlledStructureType", propOrder = {
    "controlledStructureIdentification",
    "controlledStructureExposureValue"
})
public class ComplexControlledStructureType {

    @XmlElement(name = "ControlledStructureIdentification", required = true)
    protected ComplexEntityIdentificationType controlledStructureIdentification;
    @XmlElement(name = "ControlledStructureExposureValue", required = true)
    protected BigInteger controlledStructureExposureValue;

    /**
     * Gets the value of the controlledStructureIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public ComplexEntityIdentificationType getControlledStructureIdentification() {
        return controlledStructureIdentification;
    }

    /**
     * Sets the value of the controlledStructureIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public void setControlledStructureIdentification(ComplexEntityIdentificationType value) {
        this.controlledStructureIdentification = value;
    }

    /**
     * Gets the value of the controlledStructureExposureValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getControlledStructureExposureValue() {
        return controlledStructureExposureValue;
    }

    /**
     * Sets the value of the controlledStructureExposureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setControlledStructureExposureValue(BigInteger value) {
        this.controlledStructureExposureValue = value;
    }

}
