//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexPortfolioLiquidityProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexPortfolioLiquidityProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PortfolioLiquidityInDays0to1Rate" type="{}UnsignedDecimal15p4Type"/>
 *         &lt;element name="PortfolioLiquidityInDays2to7Rate" type="{}UnsignedDecimal15p4Type"/>
 *         &lt;element name="PortfolioLiquidityInDays8to30Rate" type="{}UnsignedDecimal15p4Type"/>
 *         &lt;element name="PortfolioLiquidityInDays31to90Rate" type="{}UnsignedDecimal15p4Type"/>
 *         &lt;element name="PortfolioLiquidityInDays91to180Rate" type="{}UnsignedDecimal15p4Type"/>
 *         &lt;element name="PortfolioLiquidityInDays181to365Rate" type="{}UnsignedDecimal15p4Type"/>
 *         &lt;element name="PortfolioLiquidityInDays365MoreRate" type="{}UnsignedDecimal15p4Type"/>
 *         &lt;element name="UnencumberedCash" type="{}UnsignedInteger15pType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexPortfolioLiquidityProfileType", propOrder = {
    "portfolioLiquidityInDays0To1Rate",
    "portfolioLiquidityInDays2To7Rate",
    "portfolioLiquidityInDays8To30Rate",
    "portfolioLiquidityInDays31To90Rate",
    "portfolioLiquidityInDays91To180Rate",
    "portfolioLiquidityInDays181To365Rate",
    "portfolioLiquidityInDays365MoreRate",
    "unencumberedCash"
})
public class ComplexPortfolioLiquidityProfileType {

    @XmlElement(name = "PortfolioLiquidityInDays0to1Rate", required = true)
    protected BigDecimal portfolioLiquidityInDays0To1Rate;
    @XmlElement(name = "PortfolioLiquidityInDays2to7Rate", required = true)
    protected BigDecimal portfolioLiquidityInDays2To7Rate;
    @XmlElement(name = "PortfolioLiquidityInDays8to30Rate", required = true)
    protected BigDecimal portfolioLiquidityInDays8To30Rate;
    @XmlElement(name = "PortfolioLiquidityInDays31to90Rate", required = true)
    protected BigDecimal portfolioLiquidityInDays31To90Rate;
    @XmlElement(name = "PortfolioLiquidityInDays91to180Rate", required = true)
    protected BigDecimal portfolioLiquidityInDays91To180Rate;
    @XmlElement(name = "PortfolioLiquidityInDays181to365Rate", required = true)
    protected BigDecimal portfolioLiquidityInDays181To365Rate;
    @XmlElement(name = "PortfolioLiquidityInDays365MoreRate", required = true)
    protected BigDecimal portfolioLiquidityInDays365MoreRate;
    @XmlElement(name = "UnencumberedCash", required = true)
    protected BigInteger unencumberedCash;

    /**
     * Gets the value of the portfolioLiquidityInDays0To1Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortfolioLiquidityInDays0To1Rate() {
        return portfolioLiquidityInDays0To1Rate;
    }

    /**
     * Sets the value of the portfolioLiquidityInDays0To1Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortfolioLiquidityInDays0To1Rate(BigDecimal value) {
        this.portfolioLiquidityInDays0To1Rate = value;
    }

    /**
     * Gets the value of the portfolioLiquidityInDays2To7Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortfolioLiquidityInDays2To7Rate() {
        return portfolioLiquidityInDays2To7Rate;
    }

    /**
     * Sets the value of the portfolioLiquidityInDays2To7Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortfolioLiquidityInDays2To7Rate(BigDecimal value) {
        this.portfolioLiquidityInDays2To7Rate = value;
    }

    /**
     * Gets the value of the portfolioLiquidityInDays8To30Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortfolioLiquidityInDays8To30Rate() {
        return portfolioLiquidityInDays8To30Rate;
    }

    /**
     * Sets the value of the portfolioLiquidityInDays8To30Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortfolioLiquidityInDays8To30Rate(BigDecimal value) {
        this.portfolioLiquidityInDays8To30Rate = value;
    }

    /**
     * Gets the value of the portfolioLiquidityInDays31To90Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortfolioLiquidityInDays31To90Rate() {
        return portfolioLiquidityInDays31To90Rate;
    }

    /**
     * Sets the value of the portfolioLiquidityInDays31To90Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortfolioLiquidityInDays31To90Rate(BigDecimal value) {
        this.portfolioLiquidityInDays31To90Rate = value;
    }

    /**
     * Gets the value of the portfolioLiquidityInDays91To180Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortfolioLiquidityInDays91To180Rate() {
        return portfolioLiquidityInDays91To180Rate;
    }

    /**
     * Sets the value of the portfolioLiquidityInDays91To180Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortfolioLiquidityInDays91To180Rate(BigDecimal value) {
        this.portfolioLiquidityInDays91To180Rate = value;
    }

    /**
     * Gets the value of the portfolioLiquidityInDays181To365Rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortfolioLiquidityInDays181To365Rate() {
        return portfolioLiquidityInDays181To365Rate;
    }

    /**
     * Sets the value of the portfolioLiquidityInDays181To365Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortfolioLiquidityInDays181To365Rate(BigDecimal value) {
        this.portfolioLiquidityInDays181To365Rate = value;
    }

    /**
     * Gets the value of the portfolioLiquidityInDays365MoreRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortfolioLiquidityInDays365MoreRate() {
        return portfolioLiquidityInDays365MoreRate;
    }

    /**
     * Sets the value of the portfolioLiquidityInDays365MoreRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortfolioLiquidityInDays365MoreRate(BigDecimal value) {
        this.portfolioLiquidityInDays365MoreRate = value;
    }

    /**
     * Gets the value of the unencumberedCash property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnencumberedCash() {
        return unencumberedCash;
    }

    /**
     * Sets the value of the unencumberedCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnencumberedCash(BigInteger value) {
        this.unencumberedCash = value;
    }

}
