//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexAIFIndividualInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexAIFIndividualInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndividualExposure" type="{}ComplexIndividualExposureType"/>
 *         &lt;element name="RiskProfile" type="{}ComplexRiskProfileType"/>
 *         &lt;element name="StressTests" type="{}ComplexStressTestsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexAIFIndividualInfoType", propOrder = {
    "individualExposure",
    "riskProfile",
    "stressTests"
})
public class ComplexAIFIndividualInfoType {

    @XmlElement(name = "IndividualExposure", required = true)
    protected ComplexIndividualExposureType individualExposure;
    @XmlElement(name = "RiskProfile", required = true)
    protected ComplexRiskProfileType riskProfile;
    @XmlElement(name = "StressTests", required = true)
    protected ComplexStressTestsType stressTests;

    /**
     * Gets the value of the individualExposure property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexIndividualExposureType }
     *     
     */
    public ComplexIndividualExposureType getIndividualExposure() {
        return individualExposure;
    }

    /**
     * Sets the value of the individualExposure property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexIndividualExposureType }
     *     
     */
    public void setIndividualExposure(ComplexIndividualExposureType value) {
        this.individualExposure = value;
    }

    /**
     * Gets the value of the riskProfile property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexRiskProfileType }
     *     
     */
    public ComplexRiskProfileType getRiskProfile() {
        return riskProfile;
    }

    /**
     * Sets the value of the riskProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexRiskProfileType }
     *     
     */
    public void setRiskProfile(ComplexRiskProfileType value) {
        this.riskProfile = value;
    }

    /**
     * Gets the value of the stressTests property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexStressTestsType }
     *     
     */
    public ComplexStressTestsType getStressTests() {
        return stressTests;
    }

    /**
     * Sets the value of the stressTests property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexStressTestsType }
     *     
     */
    public void setStressTests(ComplexStressTestsType value) {
        this.stressTests = value;
    }

}
