//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexOtherArrangementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexOtherArrangementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OtherArrangementType" type="{}StringRestricted300Type"/>
 *         &lt;element name="OtherArrangementRate" type="{}UnsignedPercentType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexOtherArrangementType", propOrder = {
    "otherArrangementType",
    "otherArrangementRate"
})
public class ComplexOtherArrangementType {

    @XmlElement(name = "OtherArrangementType", required = true)
    protected String otherArrangementType;
    @XmlElement(name = "OtherArrangementRate", required = true)
    protected BigDecimal otherArrangementRate;

    /**
     * Gets the value of the otherArrangementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherArrangementType() {
        return otherArrangementType;
    }

    /**
     * Sets the value of the otherArrangementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherArrangementType(String value) {
        this.otherArrangementType = value;
    }

    /**
     * Gets the value of the otherArrangementRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOtherArrangementRate() {
        return otherArrangementRate;
    }

    /**
     * Sets the value of the otherArrangementRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOtherArrangementRate(BigDecimal value) {
        this.otherArrangementRate = value;
    }

}
