//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexHistoricalRiskProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexHistoricalRiskProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrossInvestmentReturnsRate" type="{}ComplexSignedRateMonthPeriodType" minOccurs="0"/>
 *         &lt;element name="NetInvestmentReturnsRate" type="{}ComplexSignedRateMonthPeriodType" minOccurs="0"/>
 *         &lt;element name="NAVChangeRate" type="{}ComplexSignedRateMonthPeriodType" minOccurs="0"/>
 *         &lt;element name="Subscription" type="{}ComplexQuantityMonthPeriodType" minOccurs="0"/>
 *         &lt;element name="Redemption" type="{}ComplexQuantityMonthPeriodType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexHistoricalRiskProfileType", propOrder = {
    "grossInvestmentReturnsRate",
    "netInvestmentReturnsRate",
    "navChangeRate",
    "subscription",
    "redemption"
})
public class ComplexHistoricalRiskProfileType {

    @XmlElement(name = "GrossInvestmentReturnsRate")
    protected ComplexSignedRateMonthPeriodType grossInvestmentReturnsRate;
    @XmlElement(name = "NetInvestmentReturnsRate")
    protected ComplexSignedRateMonthPeriodType netInvestmentReturnsRate;
    @XmlElement(name = "NAVChangeRate")
    protected ComplexSignedRateMonthPeriodType navChangeRate;
    @XmlElement(name = "Subscription")
    protected ComplexQuantityMonthPeriodType subscription;
    @XmlElement(name = "Redemption")
    protected ComplexQuantityMonthPeriodType redemption;

    /**
     * Gets the value of the grossInvestmentReturnsRate property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexSignedRateMonthPeriodType }
     *     
     */
    public ComplexSignedRateMonthPeriodType getGrossInvestmentReturnsRate() {
        return grossInvestmentReturnsRate;
    }

    /**
     * Sets the value of the grossInvestmentReturnsRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexSignedRateMonthPeriodType }
     *     
     */
    public void setGrossInvestmentReturnsRate(ComplexSignedRateMonthPeriodType value) {
        this.grossInvestmentReturnsRate = value;
    }

    /**
     * Gets the value of the netInvestmentReturnsRate property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexSignedRateMonthPeriodType }
     *     
     */
    public ComplexSignedRateMonthPeriodType getNetInvestmentReturnsRate() {
        return netInvestmentReturnsRate;
    }

    /**
     * Sets the value of the netInvestmentReturnsRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexSignedRateMonthPeriodType }
     *     
     */
    public void setNetInvestmentReturnsRate(ComplexSignedRateMonthPeriodType value) {
        this.netInvestmentReturnsRate = value;
    }

    /**
     * Gets the value of the navChangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexSignedRateMonthPeriodType }
     *     
     */
    public ComplexSignedRateMonthPeriodType getNAVChangeRate() {
        return navChangeRate;
    }

    /**
     * Sets the value of the navChangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexSignedRateMonthPeriodType }
     *     
     */
    public void setNAVChangeRate(ComplexSignedRateMonthPeriodType value) {
        this.navChangeRate = value;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexQuantityMonthPeriodType }
     *     
     */
    public ComplexQuantityMonthPeriodType getSubscription() {
        return subscription;
    }

    /**
     * Sets the value of the subscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexQuantityMonthPeriodType }
     *     
     */
    public void setSubscription(ComplexQuantityMonthPeriodType value) {
        this.subscription = value;
    }

    /**
     * Gets the value of the redemption property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexQuantityMonthPeriodType }
     *     
     */
    public ComplexQuantityMonthPeriodType getRedemption() {
        return redemption;
    }

    /**
     * Sets the value of the redemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexQuantityMonthPeriodType }
     *     
     */
    public void setRedemption(ComplexQuantityMonthPeriodType value) {
        this.redemption = value;
    }

}
