//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexThreePrincipalMarketType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexThreePrincipalMarketType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ranking" type="{}ThreeRankingType"/>
 *         &lt;element name="MarketIdentification" type="{}ComplexMarketIdentificationWithNOTType"/>
 *         &lt;element name="AggregatedValueAmount" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexThreePrincipalMarketType", propOrder = {
    "ranking",
    "marketIdentification",
    "aggregatedValueAmount"
})
public class ComplexThreePrincipalMarketType {

    @XmlElement(name = "Ranking", required = true)
    protected BigInteger ranking;
    @XmlElement(name = "MarketIdentification", required = true)
    protected ComplexMarketIdentificationWithNOTType marketIdentification;
    @XmlElement(name = "AggregatedValueAmount")
    protected BigInteger aggregatedValueAmount;

    /**
     * Gets the value of the ranking property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRanking() {
        return ranking;
    }

    /**
     * Sets the value of the ranking property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRanking(BigInteger value) {
        this.ranking = value;
    }

    /**
     * Gets the value of the marketIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexMarketIdentificationWithNOTType }
     *     
     */
    public ComplexMarketIdentificationWithNOTType getMarketIdentification() {
        return marketIdentification;
    }

    /**
     * Sets the value of the marketIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexMarketIdentificationWithNOTType }
     *     
     */
    public void setMarketIdentification(ComplexMarketIdentificationWithNOTType value) {
        this.marketIdentification = value;
    }

    /**
     * Gets the value of the aggregatedValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAggregatedValueAmount() {
        return aggregatedValueAmount;
    }

    /**
     * Sets the value of the aggregatedValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAggregatedValueAmount(BigInteger value) {
        this.aggregatedValueAmount = value;
    }

}
