//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexAIFPrincipalMarketsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexAIFPrincipalMarketsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AIFPrincipalMarket" type="{}ComplexThreePrincipalMarketType" maxOccurs="3" minOccurs="3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexAIFPrincipalMarketsType", propOrder = {
    "aifPrincipalMarket"
})
public class ComplexAIFPrincipalMarketsType {

    @XmlElement(name = "AIFPrincipalMarket", required = true)
    protected List<ComplexThreePrincipalMarketType> aifPrincipalMarket;

    /**
     * Gets the value of the aifPrincipalMarket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aifPrincipalMarket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAIFPrincipalMarket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComplexThreePrincipalMarketType }
     * 
     * 
     */
    public List<ComplexThreePrincipalMarketType> getAIFPrincipalMarket() {
        if (aifPrincipalMarket == null) {
            aifPrincipalMarket = new ArrayList<ComplexThreePrincipalMarketType>();
        }
        return this.aifPrincipalMarket;
    }

}
