//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ComplexAIFMRecordInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexAIFMRecordInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FilingType" type="{}FilingTypeType"/>
 *         &lt;element name="AIFMContentType" type="{}AIFMContentTypeType"/>
 *         &lt;element name="ReportingPeriodStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ReportingPeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ReportingPeriodType" type="{}ReportingPeriodTypeType"/>
 *         &lt;element name="ReportingPeriodYear" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *         &lt;element name="AIFMReportingObligationChangeFrequencyCode" type="{}ReportingObligationChangeFrequencyCodeType" minOccurs="0"/>
 *         &lt;element name="AIFMReportingObligationChangeContentsCode" type="{}AIFMReportingObligationChangeContentsCodeType" minOccurs="0"/>
 *         &lt;element name="AIFMReportingObligationChangeQuarter" type="{}ReportingObligationChangeQuarterType" minOccurs="0"/>
 *         &lt;element name="LastReportingFlag" type="{}BooleanType"/>
 *         &lt;element name="Assumptions" type="{}ComplexAssumptionsType" minOccurs="0"/>
 *         &lt;element name="AIFMReportingCode" type="{}AIFMReportingCodeType"/>
 *         &lt;element name="AIFMJurisdiction" type="{}CountryCodeType"/>
 *         &lt;element name="AIFMNationalCode" type="{}AIFMNationalCodeType"/>
 *         &lt;element name="AIFMName" type="{}StringRestricted300Type"/>
 *         &lt;element name="AIFMEEAFlag" type="{}BooleanType"/>
 *         &lt;element name="AIFMNoReportingFlag" type="{}BooleanType"/>
 *         &lt;element name="AIFMCompleteDescription" type="{}ComplexAIFMCompleteDescriptionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexAIFMRecordInfoType", propOrder = {
    "filingType",
    "aifmContentType",
    "reportingPeriodStartDate",
    "reportingPeriodEndDate",
    "reportingPeriodType",
    "reportingPeriodYear",
    "aifmReportingObligationChangeFrequencyCode",
    "aifmReportingObligationChangeContentsCode",
    "aifmReportingObligationChangeQuarter",
    "lastReportingFlag",
    "assumptions",
    "aifmReportingCode",
    "aifmJurisdiction",
    "aifmNationalCode",
    "aifmName",
    "aifmeeaFlag",
    "aifmNoReportingFlag",
    "aifmCompleteDescription"
})
public class ComplexAIFMRecordInfoType {

    @XmlElement(name = "FilingType", required = true)
    protected FilingTypeType filingType;
    @XmlElement(name = "AIFMContentType", required = true)
    protected String aifmContentType;
    @XmlElement(name = "ReportingPeriodStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reportingPeriodStartDate;
    @XmlElement(name = "ReportingPeriodEndDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar reportingPeriodEndDate;
    @XmlElement(name = "ReportingPeriodType", required = true)
    protected ReportingPeriodTypeType reportingPeriodType;
    @XmlElement(name = "ReportingPeriodYear", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar reportingPeriodYear;
    @XmlElement(name = "AIFMReportingObligationChangeFrequencyCode")
    protected ReportingObligationChangeFrequencyCodeType aifmReportingObligationChangeFrequencyCode;
    @XmlElement(name = "AIFMReportingObligationChangeContentsCode")
    protected BigInteger aifmReportingObligationChangeContentsCode;
    @XmlElement(name = "AIFMReportingObligationChangeQuarter")
    protected ReportingObligationChangeQuarterType aifmReportingObligationChangeQuarter;
    @XmlElement(name = "LastReportingFlag")
    protected boolean lastReportingFlag;
    @XmlElement(name = "Assumptions")
    protected ComplexAssumptionsType assumptions;
    @XmlElement(name = "AIFMReportingCode", required = true)
    protected BigInteger aifmReportingCode;
    @XmlElement(name = "AIFMJurisdiction", required = true)
    protected String aifmJurisdiction;
    @XmlElement(name = "AIFMNationalCode", required = true)
    protected String aifmNationalCode;
    @XmlElement(name = "AIFMName", required = true)
    protected String aifmName;
    @XmlElement(name = "AIFMEEAFlag")
    protected boolean aifmeeaFlag;
    @XmlElement(name = "AIFMNoReportingFlag")
    protected boolean aifmNoReportingFlag;
    @XmlElement(name = "AIFMCompleteDescription")
    protected ComplexAIFMCompleteDescriptionType aifmCompleteDescription;

    /**
     * Gets the value of the filingType property.
     * 
     * @return
     *     possible object is
     *     {@link FilingTypeType }
     *     
     */
    public FilingTypeType getFilingType() {
        return filingType;
    }

    /**
     * Sets the value of the filingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilingTypeType }
     *     
     */
    public void setFilingType(FilingTypeType value) {
        this.filingType = value;
    }

    /**
     * Gets the value of the aifmContentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFMContentType() {
        return aifmContentType;
    }

    /**
     * Sets the value of the aifmContentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFMContentType(String value) {
        this.aifmContentType = value;
    }

    /**
     * Gets the value of the reportingPeriodStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingPeriodStartDate() {
        return reportingPeriodStartDate;
    }

    /**
     * Sets the value of the reportingPeriodStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingPeriodStartDate(XMLGregorianCalendar value) {
        this.reportingPeriodStartDate = value;
    }

    /**
     * Gets the value of the reportingPeriodEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingPeriodEndDate() {
        return reportingPeriodEndDate;
    }

    /**
     * Sets the value of the reportingPeriodEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingPeriodEndDate(XMLGregorianCalendar value) {
        this.reportingPeriodEndDate = value;
    }

    /**
     * Gets the value of the reportingPeriodType property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingPeriodTypeType }
     *     
     */
    public ReportingPeriodTypeType getReportingPeriodType() {
        return reportingPeriodType;
    }

    /**
     * Sets the value of the reportingPeriodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingPeriodTypeType }
     *     
     */
    public void setReportingPeriodType(ReportingPeriodTypeType value) {
        this.reportingPeriodType = value;
    }

    /**
     * Gets the value of the reportingPeriodYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportingPeriodYear() {
        return reportingPeriodYear;
    }

    /**
     * Sets the value of the reportingPeriodYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportingPeriodYear(XMLGregorianCalendar value) {
        this.reportingPeriodYear = value;
    }

    /**
     * Gets the value of the aifmReportingObligationChangeFrequencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingObligationChangeFrequencyCodeType }
     *     
     */
    public ReportingObligationChangeFrequencyCodeType getAIFMReportingObligationChangeFrequencyCode() {
        return aifmReportingObligationChangeFrequencyCode;
    }

    /**
     * Sets the value of the aifmReportingObligationChangeFrequencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingObligationChangeFrequencyCodeType }
     *     
     */
    public void setAIFMReportingObligationChangeFrequencyCode(ReportingObligationChangeFrequencyCodeType value) {
        this.aifmReportingObligationChangeFrequencyCode = value;
    }

    /**
     * Gets the value of the aifmReportingObligationChangeContentsCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAIFMReportingObligationChangeContentsCode() {
        return aifmReportingObligationChangeContentsCode;
    }

    /**
     * Sets the value of the aifmReportingObligationChangeContentsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAIFMReportingObligationChangeContentsCode(BigInteger value) {
        this.aifmReportingObligationChangeContentsCode = value;
    }

    /**
     * Gets the value of the aifmReportingObligationChangeQuarter property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingObligationChangeQuarterType }
     *     
     */
    public ReportingObligationChangeQuarterType getAIFMReportingObligationChangeQuarter() {
        return aifmReportingObligationChangeQuarter;
    }

    /**
     * Sets the value of the aifmReportingObligationChangeQuarter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingObligationChangeQuarterType }
     *     
     */
    public void setAIFMReportingObligationChangeQuarter(ReportingObligationChangeQuarterType value) {
        this.aifmReportingObligationChangeQuarter = value;
    }

    /**
     * Gets the value of the lastReportingFlag property.
     * 
     */
    public boolean isLastReportingFlag() {
        return lastReportingFlag;
    }

    /**
     * Sets the value of the lastReportingFlag property.
     * 
     */
    public void setLastReportingFlag(boolean value) {
        this.lastReportingFlag = value;
    }

    /**
     * Gets the value of the assumptions property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAssumptionsType }
     *     
     */
    public ComplexAssumptionsType getAssumptions() {
        return assumptions;
    }

    /**
     * Sets the value of the assumptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAssumptionsType }
     *     
     */
    public void setAssumptions(ComplexAssumptionsType value) {
        this.assumptions = value;
    }

    /**
     * Gets the value of the aifmReportingCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAIFMReportingCode() {
        return aifmReportingCode;
    }

    /**
     * Sets the value of the aifmReportingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAIFMReportingCode(BigInteger value) {
        this.aifmReportingCode = value;
    }

    /**
     * Gets the value of the aifmJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFMJurisdiction() {
        return aifmJurisdiction;
    }

    /**
     * Sets the value of the aifmJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFMJurisdiction(String value) {
        this.aifmJurisdiction = value;
    }

    /**
     * Gets the value of the aifmNationalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFMNationalCode() {
        return aifmNationalCode;
    }

    /**
     * Sets the value of the aifmNationalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFMNationalCode(String value) {
        this.aifmNationalCode = value;
    }

    /**
     * Gets the value of the aifmName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFMName() {
        return aifmName;
    }

    /**
     * Sets the value of the aifmName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFMName(String value) {
        this.aifmName = value;
    }

    /**
     * Gets the value of the aifmeeaFlag property.
     * 
     */
    public boolean isAIFMEEAFlag() {
        return aifmeeaFlag;
    }

    /**
     * Sets the value of the aifmeeaFlag property.
     * 
     */
    public void setAIFMEEAFlag(boolean value) {
        this.aifmeeaFlag = value;
    }

    /**
     * Gets the value of the aifmNoReportingFlag property.
     * 
     */
    public boolean isAIFMNoReportingFlag() {
        return aifmNoReportingFlag;
    }

    /**
     * Sets the value of the aifmNoReportingFlag property.
     * 
     */
    public void setAIFMNoReportingFlag(boolean value) {
        this.aifmNoReportingFlag = value;
    }

    /**
     * Gets the value of the aifmCompleteDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAIFMCompleteDescriptionType }
     *     
     */
    public ComplexAIFMCompleteDescriptionType getAIFMCompleteDescription() {
        return aifmCompleteDescription;
    }

    /**
     * Sets the value of the aifmCompleteDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAIFMCompleteDescriptionType }
     *     
     */
    public void setAIFMCompleteDescription(ComplexAIFMCompleteDescriptionType value) {
        this.aifmCompleteDescription = value;
    }

}
