//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexMostImportantConcentrationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexMostImportantConcentrationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PortfolioConcentrations" type="{}ComplexPortfolioConcentrationsType"/>
 *         &lt;element name="TypicalPositionSize" type="{}TypicalPositionSizeType" minOccurs="0"/>
 *         &lt;element name="AIFPrincipalMarkets" type="{}ComplexAIFPrincipalMarketsType"/>
 *         &lt;element name="InvestorConcentration" type="{}ComplexInvestorConcentrationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexMostImportantConcentrationType", propOrder = {
    "portfolioConcentrations",
    "typicalPositionSize",
    "aifPrincipalMarkets",
    "investorConcentration"
})
public class ComplexMostImportantConcentrationType {

    @XmlElement(name = "PortfolioConcentrations", required = true)
    protected ComplexPortfolioConcentrationsType portfolioConcentrations;
    @XmlElement(name = "TypicalPositionSize")
    protected TypicalPositionSizeType typicalPositionSize;
    @XmlElement(name = "AIFPrincipalMarkets", required = true)
    protected ComplexAIFPrincipalMarketsType aifPrincipalMarkets;
    @XmlElement(name = "InvestorConcentration", required = true)
    protected ComplexInvestorConcentrationType investorConcentration;

    /**
     * Gets the value of the portfolioConcentrations property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexPortfolioConcentrationsType }
     *     
     */
    public ComplexPortfolioConcentrationsType getPortfolioConcentrations() {
        return portfolioConcentrations;
    }

    /**
     * Sets the value of the portfolioConcentrations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexPortfolioConcentrationsType }
     *     
     */
    public void setPortfolioConcentrations(ComplexPortfolioConcentrationsType value) {
        this.portfolioConcentrations = value;
    }

    /**
     * Gets the value of the typicalPositionSize property.
     * 
     * @return
     *     possible object is
     *     {@link TypicalPositionSizeType }
     *     
     */
    public TypicalPositionSizeType getTypicalPositionSize() {
        return typicalPositionSize;
    }

    /**
     * Sets the value of the typicalPositionSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypicalPositionSizeType }
     *     
     */
    public void setTypicalPositionSize(TypicalPositionSizeType value) {
        this.typicalPositionSize = value;
    }

    /**
     * Gets the value of the aifPrincipalMarkets property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAIFPrincipalMarketsType }
     *     
     */
    public ComplexAIFPrincipalMarketsType getAIFPrincipalMarkets() {
        return aifPrincipalMarkets;
    }

    /**
     * Sets the value of the aifPrincipalMarkets property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAIFPrincipalMarketsType }
     *     
     */
    public void setAIFPrincipalMarkets(ComplexAIFPrincipalMarketsType value) {
        this.aifPrincipalMarkets = value;
    }

    /**
     * Gets the value of the investorConcentration property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexInvestorConcentrationType }
     *     
     */
    public ComplexInvestorConcentrationType getInvestorConcentration() {
        return investorConcentration;
    }

    /**
     * Sets the value of the investorConcentration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexInvestorConcentrationType }
     *     
     */
    public void setInvestorConcentration(ComplexInvestorConcentrationType value) {
        this.investorConcentration = value;
    }

}
