//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexEntityIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexEntityIdentificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EntityName" type="{}StringRestricted300Type"/>
 *         &lt;element name="EntityIdentificationBIC" type="{}BICCodeType" minOccurs="0"/>
 *         &lt;element name="EntityIdentificationLEI" type="{}LEICodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexEntityIdentificationType", propOrder = {
    "entityName",
    "entityIdentificationBIC",
    "entityIdentificationLEI"
})
public class ComplexEntityIdentificationType {

    @XmlElement(name = "EntityName", required = true)
    protected String entityName;
    @XmlElement(name = "EntityIdentificationBIC")
    protected String entityIdentificationBIC;
    @XmlElement(name = "EntityIdentificationLEI")
    protected String entityIdentificationLEI;

    /**
     * Gets the value of the entityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * Sets the value of the entityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityName(String value) {
        this.entityName = value;
    }

    /**
     * Gets the value of the entityIdentificationBIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityIdentificationBIC() {
        return entityIdentificationBIC;
    }

    /**
     * Sets the value of the entityIdentificationBIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityIdentificationBIC(String value) {
        this.entityIdentificationBIC = value;
    }

    /**
     * Gets the value of the entityIdentificationLEI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityIdentificationLEI() {
        return entityIdentificationLEI;
    }

    /**
     * Sets the value of the entityIdentificationLEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityIdentificationLEI(String value) {
        this.entityIdentificationLEI = value;
    }

}
