//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexCCPExposureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexCCPExposureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ranking" type="{}ThreeRankingType"/>
 *         &lt;element name="CCPIdentification" type="{}ComplexEntityIdentificationType"/>
 *         &lt;element name="CCPExposureValue" type="{}UnsignedInteger15pType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexCCPExposureType", propOrder = {
    "ranking",
    "ccpIdentification",
    "ccpExposureValue"
})
public class ComplexCCPExposureType {

    @XmlElement(name = "Ranking", required = true)
    protected BigInteger ranking;
    @XmlElement(name = "CCPIdentification", required = true)
    protected ComplexEntityIdentificationType ccpIdentification;
    @XmlElement(name = "CCPExposureValue", required = true)
    protected BigInteger ccpExposureValue;

    /**
     * Gets the value of the ranking property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRanking() {
        return ranking;
    }

    /**
     * Sets the value of the ranking property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRanking(BigInteger value) {
        this.ranking = value;
    }

    /**
     * Gets the value of the ccpIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public ComplexEntityIdentificationType getCCPIdentification() {
        return ccpIdentification;
    }

    /**
     * Sets the value of the ccpIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexEntityIdentificationType }
     *     
     */
    public void setCCPIdentification(ComplexEntityIdentificationType value) {
        this.ccpIdentification = value;
    }

    /**
     * Gets the value of the ccpExposureValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCCPExposureValue() {
        return ccpExposureValue;
    }

    /**
     * Sets the value of the ccpExposureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCCPExposureValue(BigInteger value) {
        this.ccpExposureValue = value;
    }

}
