//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexSecuritiesCashBorrowingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexSecuritiesCashBorrowingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UnsecuredBorrowingAmount" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *         &lt;element name="SecuredBorrowingPrimeBrokerageAmount" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *         &lt;element name="SecuredBorrowingReverseRepoAmount" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *         &lt;element name="SecuredBorrowingOtherAmount" type="{}UnsignedInteger15pType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexSecuritiesCashBorrowingType", propOrder = {
    "unsecuredBorrowingAmount",
    "securedBorrowingPrimeBrokerageAmount",
    "securedBorrowingReverseRepoAmount",
    "securedBorrowingOtherAmount"
})
public class ComplexSecuritiesCashBorrowingType {

    @XmlElement(name = "UnsecuredBorrowingAmount")
    protected BigInteger unsecuredBorrowingAmount;
    @XmlElement(name = "SecuredBorrowingPrimeBrokerageAmount")
    protected BigInteger securedBorrowingPrimeBrokerageAmount;
    @XmlElement(name = "SecuredBorrowingReverseRepoAmount")
    protected BigInteger securedBorrowingReverseRepoAmount;
    @XmlElement(name = "SecuredBorrowingOtherAmount")
    protected BigInteger securedBorrowingOtherAmount;

    /**
     * Gets the value of the unsecuredBorrowingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnsecuredBorrowingAmount() {
        return unsecuredBorrowingAmount;
    }

    /**
     * Sets the value of the unsecuredBorrowingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnsecuredBorrowingAmount(BigInteger value) {
        this.unsecuredBorrowingAmount = value;
    }

    /**
     * Gets the value of the securedBorrowingPrimeBrokerageAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSecuredBorrowingPrimeBrokerageAmount() {
        return securedBorrowingPrimeBrokerageAmount;
    }

    /**
     * Sets the value of the securedBorrowingPrimeBrokerageAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSecuredBorrowingPrimeBrokerageAmount(BigInteger value) {
        this.securedBorrowingPrimeBrokerageAmount = value;
    }

    /**
     * Gets the value of the securedBorrowingReverseRepoAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSecuredBorrowingReverseRepoAmount() {
        return securedBorrowingReverseRepoAmount;
    }

    /**
     * Sets the value of the securedBorrowingReverseRepoAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSecuredBorrowingReverseRepoAmount(BigInteger value) {
        this.securedBorrowingReverseRepoAmount = value;
    }

    /**
     * Gets the value of the securedBorrowingOtherAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSecuredBorrowingOtherAmount() {
        return securedBorrowingOtherAmount;
    }

    /**
     * Sets the value of the securedBorrowingOtherAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSecuredBorrowingOtherAmount(BigInteger value) {
        this.securedBorrowingOtherAmount = value;
    }

}
