//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComplexAIFIdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexAIFIdentifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AIFIdentifierLEI" type="{}LEICodeType" minOccurs="0"/>
 *         &lt;element name="AIFIdentifierISIN" type="{}ISINInstrumentIdentificationType" minOccurs="0"/>
 *         &lt;element name="AIFIdentifierCUSIP" type="{}CusipCodeType" minOccurs="0"/>
 *         &lt;element name="AIFIdentifierSEDOL" type="{}SedolCodeType" minOccurs="0"/>
 *         &lt;element name="AIFIdentifierTicker" type="{}TickerCodeType" minOccurs="0"/>
 *         &lt;element name="AIFIdentifierRIC" type="{}RICCodeType" minOccurs="0"/>
 *         &lt;element name="AIFIdentifierECB" type="{}ECBCodeType" minOccurs="0"/>
 *         &lt;element name="OldAIFIdentifierNCA" type="{}ComplexAIFNationalIdentifierType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexAIFIdentifierType", propOrder = {
    "aifIdentifierLEI",
    "aifIdentifierISIN",
    "aifIdentifierCUSIP",
    "aifIdentifierSEDOL",
    "aifIdentifierTicker",
    "aifIdentifierRIC",
    "aifIdentifierECB",
    "oldAIFIdentifierNCA"
})
public class ComplexAIFIdentifierType {

    @XmlElement(name = "AIFIdentifierLEI")
    protected String aifIdentifierLEI;
    @XmlElement(name = "AIFIdentifierISIN")
    protected String aifIdentifierISIN;
    @XmlElement(name = "AIFIdentifierCUSIP")
    protected String aifIdentifierCUSIP;
    @XmlElement(name = "AIFIdentifierSEDOL")
    protected String aifIdentifierSEDOL;
    @XmlElement(name = "AIFIdentifierTicker")
    protected String aifIdentifierTicker;
    @XmlElement(name = "AIFIdentifierRIC")
    protected String aifIdentifierRIC;
    @XmlElement(name = "AIFIdentifierECB")
    protected String aifIdentifierECB;
    @XmlElement(name = "OldAIFIdentifierNCA")
    protected ComplexAIFNationalIdentifierType oldAIFIdentifierNCA;

    /**
     * Gets the value of the aifIdentifierLEI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFIdentifierLEI() {
        return aifIdentifierLEI;
    }

    /**
     * Sets the value of the aifIdentifierLEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFIdentifierLEI(String value) {
        this.aifIdentifierLEI = value;
    }

    /**
     * Gets the value of the aifIdentifierISIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFIdentifierISIN() {
        return aifIdentifierISIN;
    }

    /**
     * Sets the value of the aifIdentifierISIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFIdentifierISIN(String value) {
        this.aifIdentifierISIN = value;
    }

    /**
     * Gets the value of the aifIdentifierCUSIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFIdentifierCUSIP() {
        return aifIdentifierCUSIP;
    }

    /**
     * Sets the value of the aifIdentifierCUSIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFIdentifierCUSIP(String value) {
        this.aifIdentifierCUSIP = value;
    }

    /**
     * Gets the value of the aifIdentifierSEDOL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFIdentifierSEDOL() {
        return aifIdentifierSEDOL;
    }

    /**
     * Sets the value of the aifIdentifierSEDOL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFIdentifierSEDOL(String value) {
        this.aifIdentifierSEDOL = value;
    }

    /**
     * Gets the value of the aifIdentifierTicker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFIdentifierTicker() {
        return aifIdentifierTicker;
    }

    /**
     * Sets the value of the aifIdentifierTicker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFIdentifierTicker(String value) {
        this.aifIdentifierTicker = value;
    }

    /**
     * Gets the value of the aifIdentifierRIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFIdentifierRIC() {
        return aifIdentifierRIC;
    }

    /**
     * Sets the value of the aifIdentifierRIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFIdentifierRIC(String value) {
        this.aifIdentifierRIC = value;
    }

    /**
     * Gets the value of the aifIdentifierECB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIFIdentifierECB() {
        return aifIdentifierECB;
    }

    /**
     * Sets the value of the aifIdentifierECB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIFIdentifierECB(String value) {
        this.aifIdentifierECB = value;
    }

    /**
     * Gets the value of the oldAIFIdentifierNCA property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexAIFNationalIdentifierType }
     *     
     */
    public ComplexAIFNationalIdentifierType getOldAIFIdentifierNCA() {
        return oldAIFIdentifierNCA;
    }

    /**
     * Sets the value of the oldAIFIdentifierNCA property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexAIFNationalIdentifierType }
     *     
     */
    public void setOldAIFIdentifierNCA(ComplexAIFNationalIdentifierType value) {
        this.oldAIFIdentifierNCA = value;
    }

}
