//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HedgeFundStrategyTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HedgeFundStrategyTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EQTY_LGBS"/>
 *     &lt;enumeration value="EQTY_LGST"/>
 *     &lt;enumeration value="EQTY_MTNL"/>
 *     &lt;enumeration value="EQTY_STBS"/>
 *     &lt;enumeration value="RELV_FXIA"/>
 *     &lt;enumeration value="RELV_CBAR"/>
 *     &lt;enumeration value="RELV_VLAR"/>
 *     &lt;enumeration value="EVDR_DSRS"/>
 *     &lt;enumeration value="EVDR_RAMA"/>
 *     &lt;enumeration value="EVDR_EYSS"/>
 *     &lt;enumeration value="CRED_LGST"/>
 *     &lt;enumeration value="CRED_ABLG"/>
 *     &lt;enumeration value="MACR_MACR"/>
 *     &lt;enumeration value="MANF_CTAF"/>
 *     &lt;enumeration value="MANF_CTAQ"/>
 *     &lt;enumeration value="MULT_HFND"/>
 *     &lt;enumeration value="OTHR_HFND"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HedgeFundStrategyTypeType")
@XmlEnum
public enum HedgeFundStrategyTypeType {

    EQTY_LGBS,
    EQTY_LGST,
    EQTY_MTNL,
    EQTY_STBS,
    RELV_FXIA,
    RELV_CBAR,
    RELV_VLAR,
    EVDR_DSRS,
    EVDR_RAMA,
    EVDR_EYSS,
    CRED_LGST,
    CRED_ABLG,
    MACR_MACR,
    MANF_CTAF,
    MANF_CTAQ,
    MULT_HFND,
    OTHR_HFND;

    public String value() {
        return name();
    }

    public static HedgeFundStrategyTypeType fromValue(String v) {
        return valueOf(v);
    }

}
