//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RiskMeasureTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RiskMeasureTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NET_EQTY_DELTA"/>
 *     &lt;enumeration value="NET_DV01"/>
 *     &lt;enumeration value="NET_CS01"/>
 *     &lt;enumeration value="VAR"/>
 *     &lt;enumeration value="VEGA_EXPO"/>
 *     &lt;enumeration value="NET_FX_DELTA"/>
 *     &lt;enumeration value="NET_CTY_DELTA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RiskMeasureTypeType")
@XmlEnum
public enum RiskMeasureTypeType {

    NET_EQTY_DELTA("NET_EQTY_DELTA"),
    @XmlEnumValue("NET_DV01")
    NET_DV_01("NET_DV01"),
    @XmlEnumValue("NET_CS01")
    NET_CS_01("NET_CS01"),
    VAR("VAR"),
    VEGA_EXPO("VEGA_EXPO"),
    NET_FX_DELTA("NET_FX_DELTA"),
    NET_CTY_DELTA("NET_CTY_DELTA");
    private final String value;

    RiskMeasureTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RiskMeasureTypeType fromValue(String v) {
        for (RiskMeasureTypeType c: RiskMeasureTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
