//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransactionTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ACAP"/>
 *     &lt;enumeration value="BOUT"/>
 *     &lt;enumeration value="CONS"/>
 *     &lt;enumeration value="CDIV"/>
 *     &lt;enumeration value="ESOP"/>
 *     &lt;enumeration value="GCAP"/>
 *     &lt;enumeration value="RCAP"/>
 *     &lt;enumeration value="SLIQ"/>
 *     &lt;enumeration value="TURN"/>
 *     &lt;enumeration value="OTHR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransactionTypeType")
@XmlEnum
public enum TransactionTypeType {

    ACAP,
    BOUT,
    CONS,
    CDIV,
    ESOP,
    GCAP,
    RCAP,
    SLIQ,
    TURN,
    OTHR;

    public String value() {
        return name();
    }

    public static TransactionTypeType fromValue(String v) {
        return valueOf(v);
    }

}
