//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TurnoverSubAssetTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TurnoverSubAssetTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SEC_CSH_CSH"/>
 *     &lt;enumeration value="SEC_LEQ_LEQ"/>
 *     &lt;enumeration value="SEC_UEQ_UEQ"/>
 *     &lt;enumeration value="SEC_CPN_IVG"/>
 *     &lt;enumeration value="SEC_CPN_NIG"/>
 *     &lt;enumeration value="SEC_CPI_CPI"/>
 *     &lt;enumeration value="SEC_SBD_EUB"/>
 *     &lt;enumeration value="SEC_SBD_NEU"/>
 *     &lt;enumeration value="SEC_MUN_MUN"/>
 *     &lt;enumeration value="SEC_CBD_CBD"/>
 *     &lt;enumeration value="SEC_LON_LON"/>
 *     &lt;enumeration value="SEC_SSP_SSP"/>
 *     &lt;enumeration value="DER_EQD_EQD"/>
 *     &lt;enumeration value="DER_FID_FID"/>
 *     &lt;enumeration value="DER_CDS_CDS"/>
 *     &lt;enumeration value="DER_FEX_INV"/>
 *     &lt;enumeration value="DER_FEX_HED"/>
 *     &lt;enumeration value="DER_IRD_IRD"/>
 *     &lt;enumeration value="DER_CTY_CTY"/>
 *     &lt;enumeration value="DER_OTH_OTH"/>
 *     &lt;enumeration value="PHY_RES_RES"/>
 *     &lt;enumeration value="PHY_CTY_CTY"/>
 *     &lt;enumeration value="PHY_TIM_TIM"/>
 *     &lt;enumeration value="PHY_ART_ART"/>
 *     &lt;enumeration value="PHY_TPT_TPT"/>
 *     &lt;enumeration value="PHY_OTH_OTH"/>
 *     &lt;enumeration value="CIU_CIU_CIU"/>
 *     &lt;enumeration value="OTH_OTH_OTH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TurnoverSubAssetTypeType")
@XmlEnum
public enum TurnoverSubAssetTypeType {

    SEC_CSH_CSH,
    SEC_LEQ_LEQ,
    SEC_UEQ_UEQ,
    SEC_CPN_IVG,
    SEC_CPN_NIG,
    SEC_CPI_CPI,
    SEC_SBD_EUB,
    SEC_SBD_NEU,
    SEC_MUN_MUN,
    SEC_CBD_CBD,
    SEC_LON_LON,
    SEC_SSP_SSP,
    DER_EQD_EQD,
    DER_FID_FID,
    DER_CDS_CDS,
    DER_FEX_INV,
    DER_FEX_HED,
    DER_IRD_IRD,
    DER_CTY_CTY,
    DER_OTH_OTH,
    PHY_RES_RES,
    PHY_CTY_CTY,
    PHY_TIM_TIM,
    PHY_ART_ART,
    PHY_TPT_TPT,
    PHY_OTH_OTH,
    CIU_CIU_CIU,
    OTH_OTH_OTH;

    public String value() {
        return name();
    }

    public static TurnoverSubAssetTypeType fromValue(String v) {
        return valueOf(v);
    }

}
