//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.19 at 04:23:50 PM CET 
//


package com.reportingtool.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypicalPositionSizeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TypicalPositionSizeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="V_SMALL"/>
 *     &lt;enumeration value="SMALL"/>
 *     &lt;enumeration value="LOW_MID_MKT"/>
 *     &lt;enumeration value="UP_MID_MKT"/>
 *     &lt;enumeration value="L_CAP"/>
 *     &lt;enumeration value="M_CAP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TypicalPositionSizeType")
@XmlEnum
public enum TypicalPositionSizeType {

    V_SMALL,
    SMALL,
    LOW_MID_MKT,
    UP_MID_MKT,
    L_CAP,
    M_CAP;

    public String value() {
        return name();
    }

    public static TypicalPositionSizeType fromValue(String v) {
        return valueOf(v);
    }

}
