package com.entities.entity.usermanager;

// Generated 11-feb-2015 16:49:54 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Version;

import com.entities.utilities.hibernate.VersionAuditor;
import com.entities.utilities.hibernate.VersionableAdapter;

/**
 * UserRol generated by hbm2java
 */
@Entity
@Table(name = "T_USER_ROL")
public class UserRol implements VersionableAdapter {

	private long id;
	private String rolName;
	private String rolDesc;
	private BigDecimal rolWeight;
	private List<UserRolPermission> userRolPermissions = new ArrayList<UserRolPermission>();
	private List<User> users = new ArrayList<User>();

	@Embedded
	private VersionAuditor versionAuditor;
	@Version
	@Column(name = "VERSION", nullable = false)
	int version;

	public UserRol() {
	}

	public UserRol(long rolId, String rolName, BigDecimal rolWeight,
			VersionAuditor versionAuditor) {
		this.id = rolId;
		this.rolName = rolName;
		this.rolWeight = rolWeight;
		this.versionAuditor = versionAuditor;
	}

	public UserRol(String rolName, String rolDesc, BigDecimal rolWeight,
			List<UserRolPermission> userRolPermissions, List<User> users,
			VersionAuditor versionAuditor) {
		this.rolName = rolName;
		this.rolDesc = rolDesc;
		this.rolWeight = rolWeight;
		this.userRolPermissions = userRolPermissions;
		this.users = users;
		this.versionAuditor = versionAuditor;
	}

	@Id
	@SequenceGenerator(name = "GEN_USER_ROL", sequenceName = "SEQ_USER_ROL", initialValue = 1, allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_USER_ROL")
	@Column(name = "ROL_ID", unique = true, nullable = false, length = 10)
	public long getId() {
		return this.id;
	}

	public void setId(long rolId) {
		this.id = rolId;
	}

	@Column(name = "ROL_NAME", nullable = false, length = 40)
	public String getRolName() {
		return this.rolName;
	}

	public void setRolName(String rolName) {
		this.rolName = rolName;
	}

	@Column(name = "ROL_DESC")
	public String getRolDesc() {
		return this.rolDesc;
	}

	public void setRolDesc(String rolDesc) {
		this.rolDesc = rolDesc;
	}

	@Column(name = "ROL_WEIGHT", precision = 22, scale = 0)
	public BigDecimal getRolWeight() {
		return this.rolWeight;
	}

	public void setRolWeight(BigDecimal rolWeight) {
		this.rolWeight = rolWeight;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRol")
	public List<UserRolPermission> getUserRolPermissions() {
		return this.userRolPermissions;
	}

	public void setUserRolPermissions(List<UserRolPermission> userRolPermissions) {
		this.userRolPermissions = userRolPermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRol")
	public List<User> getUsers() {
		return this.users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	public VersionAuditor getVersionAuditor() {
		return versionAuditor;
	}

	public void setVersionAuditor(VersionAuditor _auditor) {
		this.versionAuditor = _auditor;
	}

	@Override
	public boolean equals(Object object) {
		if (object instanceof UserRol) {
			return ((UserRol) object).getRolName().equals(this.rolName);
		}
		return false;
	}
}
