package com.entities.entity.usermanager;

// Generated 11-feb-2015 16:49:54 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.entities.entity.reportingtool.Company;
import com.entities.utilities.hibernate.VersionAuditor;
import com.entities.utilities.hibernate.VersionableAdapter;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "T_USER")
public class User implements VersionableAdapter {

	private long id;
	private UserRol userRol;
	private String userName;
	private String userPass;
	private String userMail;
	private boolean enabled;
	private Date lastLoginTms;
	private List<UserControl> userControls = new ArrayList<UserControl>();
	private Company company;

	@Embedded
	private VersionAuditor versionAuditor;
	@Version
	@Column(name = "VERSION", nullable = false)
	int version;

	public User() {
	}

	public User(long userId, UserRol userRol, String userName, String userPass,
			VersionAuditor versionAuditor) {
		this.id = userId;
		this.userRol = userRol;
		this.userName = userName;
		this.userPass = userPass;
		this.versionAuditor = versionAuditor;
	}

	public User(UserRol userRol, String userName, String userPass,
			String userMail,  boolean enabled, Date lastLoginTms, Company company, VersionAuditor versionAuditor) {
		this.userRol = userRol;
		this.userName = userName;
		this.userPass = userPass;
		this.userMail = userMail;
		this.enabled = enabled;
		this.lastLoginTms = lastLoginTms;
		this.company = company;
		this.versionAuditor = versionAuditor;
	}

	@Id
	@SequenceGenerator(name = "GEN_USER", sequenceName = "SEQ_USER", initialValue = 1, allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_USER")
	@Column(name = "USER_ID", unique = true, nullable = false, length = 40)
	public long getId() {
		return this.id;
	}

	public void setId(long userId) {
		this.id = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_ID", nullable = false, foreignKey = @ForeignKey(name = "T_USER_FK_ROL_ID"))
	public UserRol getUserRol() {
		return this.userRol;
	}

	public void setUserRol(UserRol userRol) {
		this.userRol = userRol;
	}

	@Column(name = "USER_NAME", nullable = false, length = 40)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "USER_PASS", nullable = false, length = 128)
	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	@Column(name = "USER_MAIL")
	public String getUserMail() {
		return this.userMail;
	}

	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}
	
	@Column(name = "USER_ENABLED", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_LOGIN_TMS", length = 7)
	public Date getLastLoginTms() {
		return this.lastLoginTms;
	}

	public void setLastLoginTms(Date lastLoginTms) {
		this.lastLoginTms = lastLoginTms;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public List<UserControl> getUserControls() {
		return this.userControls;
	}

	public void setUserControls(List<UserControl> userControls) {
		this.userControls = userControls;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANY_ID", foreignKey = @ForeignKey(name = "T_USER_FK_COMPANY"))
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	public VersionAuditor getVersionAuditor() {
		return versionAuditor;
	}

	public void setVersionAuditor(VersionAuditor _auditor) {
		this.versionAuditor = _auditor;
	}

	@Override
	public boolean equals(Object object) {
		if (object instanceof User) {
			return ((User) object).getUserName().equals(this.userName);
		}
		return false;
	}

}
